Starting Container

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

 

For further information visit https://errors.pydantic.dev/2.10/u/import-error

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

  	For further information visit https://errors.pydantic.dev/2.10/u/import-error

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

 

For further information visit https://errors.pydantic.dev/2.10/u/import-error

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

 

For further information visit https://errors.pydantic.dev/2.10/u/import-error

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

 

For further information visit https://errors.pydantic.dev/2.10/u/import-error

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

 

For further information visit https://errors.pydantic.dev/2.10/u/import-error

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

 

For further information visit https://errors.pydantic.dev/2.10/u/import-error

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

 

For further information visit https://errors.pydantic.dev/2.10/u/import-error

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

 

For further information visit https://errors.pydantic.dev/2.10/u/import-error

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

 

For further information visit https://errors.pydantic.dev/2.10/u/import-error

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 3, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 9, in <module>

    from pydantic import BaseSettings

  File "/app/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 412, in __getattr__

    return _getattr_migration(attr_name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 296, in wrapper

    raise PydanticImportError(

pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.

 

For further information visit https://errors.pydantic.dev/2.10/u/import-error
