email error logs! 

                     tures/Space.                                       

                    DEBUG    2025-08-22 01:31:52 - DEBUG    - local  local.py:67

                             - File People Avatar-02-09.svg                     

                             retrieved successfully from flow                   

                             /app/data/.cache/axiestudio/profile_pic            

                             tures/People.                                      

[08/22/25 01:31:58] DEBUG    2025-08-22 01:31:58 - DEBUG    - local  local.py:67

                             - File 046-rocket.svg retrieved                    

                             successfully from flow                             

                             /app/data/.cache/axiestudio/profile_pic            

                             tures/Space.                                       

[08/22/25 01:34:18] INFO     2025-08-22 01:34:18 -     email_verification.py:513

                             INFO     -                                         

                             email_verification - 🔄                            

                             Resend code request for                            

                             email:                                             

                             rtnyrtuytjn@gmail.com                              

                    INFO     2025-08-22 01:34:18 - INFO     -     service.py:579

                             service - 📧 Preparing to send email               

                             to rtnyrtuytjn@gmail.com                           

                    DEBUG    2025-08-22 01:34:18 - DEBUG    -     service.py:596

                             service - 📧 Connecting to SMTP                    

                             server: smtp-relay.brevo.com:587                   

                    DEBUG    2025-08-22 01:34:18 - DEBUG    -     service.py:602

                             service - 🔒 TLS encryption enabled                

[08/22/25 01:34:19] DEBUG    2025-08-22 01:34:19 - DEBUG    -     service.py:606

                             service - ✅ SMTP authentication                   

                             successful                                         

                    INFO     2025-08-22 01:34:19 - INFO     -     service.py:610

                             service - ✅ Email sent successfully               

                             to rtnyrtuytjn@gmail.com                           

                    INFO     2025-08-22 01:34:19 - INFO     -     service.py:259

                             service - ✅ Verification code email               

                             sent successfully to                               

                             rtnyrtuytjn@gmail.com                              

                    INFO     2025-08-22 01:34:19 -     email_verification.py:569

                             INFO     -                                         

                             email_verification - ✅                            

                             New verification code                              

                             sent to                                            

                             rtnyrtuytjn@gmail.com                              

[08/22/25 01:34:36] INFO     2025-08-22 01:34:36 -     email_verification.py:361

                             INFO     -                                         

                             email_verification - 🔍                            

                             6-digit code verification                          

                             attempt for email:                                 

                             rtnyrtuytjn@gmail.com                              

                    INFO     2025-08-22 01:34:36 -     email_verification.py:377

                             INFO     -                                         

                             email_verification - ✅                            

                             Found user for code                                

                             verification: ryy                                  

                    ERROR    2025-08-22 01:34:36 - ERROR    - main - main.py:468

                             unhandled error: can't compare                     

                             offset-naive and offset-aware datetimes            


    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 120, in dispatch

    |     response = await call_next(request)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__

    |     await self.simple_response(scope, receive, send, request_headers=headers)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    |     await self.app(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/middleware.py", line 59, in __call__

    |     await self.app(scope, wrapper, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    |     await app(scope, receive, sender)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__

    |     await self.middleware_stack(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app

    |     await route.handle(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

    |     await self.app(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    |     await app(scope, receive, sender)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    |     response = await f(request)

    |                ^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app

    |     raw_response = await run_endpoint_function(

    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function

    |     return await dependant.call(**values)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 393, in verify_code

    |     validation_result = validate_code(

    |                         ^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/auth/verification_code.py", line 244, in validate_code

    |     if VerificationCodeService.is_code_expired(expiry):

    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/auth/verification_code.py", line 83, in is_code_expired

    |     expired = now > expiry_time

    |               ^^^^^^^^^^^^^^^^^

    | TypeError: can't compare offset-naive and offset-aware datetimes

    +------------------------------------

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    return await self.app(scope, receive, send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 745, in __call__

    await self.app(scope, otel_receive, otel_send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 432, in flatten_query_string_lists

    return await call_next(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

    response = await self.dispatch_func(request, call_next)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 422, in check_boundary

    return await call_next(request)

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 120, in dispatch

    response = await call_next(request)

               ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__

    await self.simple_response(scope, receive, send, request_headers=headers)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/middleware.py", line 59, in __call__

    await self.app(scope, wrapper, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

    await wrap_app_handling_exceptions(app, request)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    response = await f(request)

               ^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app

    raw_response = await run_endpoint_function(

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function

    return await dependant.call(**values)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 393, in verify_code

    validation_result = validate_code(

                        ^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/auth/verification_code.py", line 244, in validate_code

    if VerificationCodeService.is_code_expired(expiry):

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/auth/verification_code.py", line 83, in is_code_expired

    expired = now > expiry_time

              ^^^^^^^^^^^^^^^^^

TypeError: can't compare offset-naive and offset-aware datetimes

[08/22/25 01:35:00] INFO     2025-08-22 01:35:00 -     email_verification.py:361
                             email_verification - 🔍                            

                             6-digit code verification                          

                             attempt for email:                                 

                             rtnyrtuytjn@gmail.com                              

                    INFO     2025-08-22 01:35:00 -     email_verification.py:377

                             INFO     -                                         

                             email_verification - ✅                            

                             Found user for code                                

                             verification: ryy                                  

                    ERROR    2025-08-22 01:35:00 - ERROR    - main - main.py:468

                             unhandled error: can't compare                     

                             offset-naive and offset-aware datetimes            

Exception in ASGI application

  + Exception Group Traceback (most recent call last):

  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 76, in collapse_excgroups

  |     yield

  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 177, in __call__

  |     async with anyio.create_task_group() as task_group:

  |                ^^^^^^^^^^^^^^^^^^^^^^^^^

  |   File "/app/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 772, in __aexit__

  |     raise BaseExceptionGroup(

  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)

  +-+---------------- 1 ----------------

    | Traceback (most recent call last):

    |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi

    |     result = await app(  # type: ignore[func-returns-value]

    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    |     return await self.app(scope, receive, send)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__

    |     await super().__call__(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__

    |     await self.middleware_stack(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    |     await self.app(scope, receive, _send)

    |   File "/app/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 745, in __call__

    |     await self.app(scope, otel_receive, otel_send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    |     await self.app(scope, receive, _send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 432, in flatten_query_string_lists

    |     return await call_next(request)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 422, in check_boundary

    |     return await call_next(request)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 120, in dispatch

    |     response = await call_next(request)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__

    |     await self.simple_response(scope, receive, send, request_headers=headers)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    |     await self.app(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/middleware.py", line 59, in __call__

    |     await self.app(scope, wrapper, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    |     await app(scope, receive, sender)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__

    |     await self.middleware_stack(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app

    |     await route.handle(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

    |     await self.app(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    |     await app(scope, receive, sender)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    |     response = await f(request)

    |                ^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app

    |     raw_response = await run_endpoint_function(

    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function

    |     return await dependant.call(**values)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 393, in verify_code

    |     validation_result = validate_code(

    |                         ^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/auth/verification_code.py", line 244, in validate_code

    |     if VerificationCodeService.is_code_expired(expiry):

    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/auth/verification_code.py", line 83, in is_code_expired

    |     expired = now > expiry_time

    |               ^^^^^^^^^^^^^^^^^

    | TypeError: can't compare offset-naive and offset-aware datetimes

    +------------------------------------

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    return await self.app(scope, receive, send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 745, in __call__

    await self.app(scope, otel_receive, otel_send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 432, in flatten_query_string_lists

    return await call_next(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 422, in check_boundary

    return await call_next(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 120, in dispatch

    response = await call_next(request)

               ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__

    await self.simple_response(scope, receive, send, request_headers=headers)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/middleware.py", line 59, in __call__

    await self.app(scope, wrapper, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

    await wrap_app_handling_exceptions(app, request)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    response = await f(request)

               ^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app

    raw_response = await run_endpoint_function(

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function

    return await dependant.call(**values)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 393, in verify_code

    validation_result = validate_code(

                        ^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/auth/verification_code.py", line 244, in validate_code

    if VerificationCodeService.is_code_expired(expiry):

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/auth/verification_code.py", line 83, in is_code_expired

    expired = now > expiry_time

              ^^^^^^^^^^^^^^^^^

TypeError: can't compare offset-naive and offset-aware datetimes



