You reached the start of the range → Aug 21, 2025, 5:39 PM

                             logger - Logger set up with log                    

                             level: debug                                       

                    DEBUG    2025-08-21 15:40:41 - DEBUG    -      manager.py:55

                             manager - Create service                           

                             ServiceType.TELEMETRY_SERVICE                      


/ Starting Core Services...
- Starting Core Services...
+ Starting Core Services


\ Connecting Database...
+ Connecting Database


| Loading Components...
+ Loading Components


/ Adding Starter Projects...
+ Adding Starter Projects


- Launching Axie Studio...[08/21/25 15:40:42] DEBUG    2025-08-21 15:40:42 - DEBUG    -    __main__.py:111

                             __main__ - Number of workers: 1                    

[08/21/25 15:40:42] DEBUG    2025-08-21 15:40:42 - DEBUG    -      logger.py:231

                             logger - Cache directory:                          

                             /app/data/.cache/axiestudio                        

                    DEBUG    2025-08-21 15:40:42 - DEBUG    -      logger.py:233

                             logger - Log file:                                 

                             /app/data/.cache/axiestudio/axiestudi              

                             o.log                                              

                    DEBUG    2025-08-21 15:40:42 - DEBUG    -      logger.py:255

                             logger - Logger set up with log                    

                             level: debug                                       

                    DEBUG    2025-08-21 15:40:42 - DEBUG    - main - main.py:135

                             Starting Axie Studio v1.5.0.post1...               

                    DEBUG    2025-08-21 15:40:42 - DEBUG    - main - main.py:145

                             Initializing services                              

                    DEBUG    2025-08-21 15:40:42 - DEBUG    -      manager.py:55

                             manager - Create service                           

                             ServiceType.CACHE_SERVICE                          

                    DEBUG    2025-08-21 15:40:42 - DEBUG    - utils  utils.py:17

                             - Initializing database                            

                    DEBUG    2025-08-21 15:40:42 - DEBUG    -      manager.py:55

                             manager - Create service                           

                             ServiceType.DATABASE_SERVICE                       


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...[08/21/25 15:40:43] DEBUG    2025-08-21 15:40:43 - DEBUG    -     service.py:438

                             service - Database and tables                      

                             already exist                                      

                    DEBUG    2025-08-21 15:40:43 - DEBUG    -     service.py:298

                             service - Missing column:                          

                             login_attempts in table user                       


- Launching Axie Studio...                    DEBUG    2025-08-21 15:40:43 - DEBUG    -     service.py:342

                             service - Alembic initialized                      


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...

[08/21/25 15:40:44] DEBUG    2025-08-21 15:40:44 - DEBUG    -     service.py:348

                             service - Error checking migrations:               

                             New upgrade operations detected:                   

                             [('add_column', None, 'user',                      

                             Column('login_attempts', Integer(),                

                             table=<user>, nullable=False,                      

                             default=ScalarElementColumnDefault(0               

                             ))), ('add_column', None, 'user',                  

                             Column('locked_until', DateTime(),                 

                             table=<user>)), ('add_column', None,               

                             'user', Column('last_login_ip',                    

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('password_changed_at',                      

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('failed_login_attempts',                    

                             Integer(), table=<user>,                           

                             nullable=False,                                    

                             default=ScalarElementColumnDefault(0               

                             ))), ('add_column', None, 'user',                  

                             Column('last_failed_login',                        

                             DateTime(), table=<user>))]                        


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...[08/21/25 15:40:49] ERROR    2025-08-21 15:40:49 - ERROR    -     service.py:357

                             service - Error checking migrations                

                             Traceback (most recent call last):                 

                                                                                

                               File                                             

                             "/usr/local/lib/python3.12/threading               

                             .py", line 1030, in _bootstrap                     

                                 self._bootstrap_inner()                        

                                 |    -> <function                              

                             Thread._bootstrap_inner at                         

                             0x7f957cee4860>                                    

                                 -> <Thread(asyncio_0, started                  

                             140277574489792)>                                  

                               File                                             

                             "/usr/local/lib/python3.12/threading               

                             .py", line 1073, in _bootstrap_inner               

                                 self.run()                                     

                                 |    -> <function Thread.run at                

                             0x7f957cee4540>                                    

                                 -> <Thread(asyncio_0, started                  

                             140277574489792)>                                  

                               File                                             

                             "/usr/local/lib/python3.12/threading               

                             _WorkItem.run at 0x7f95029a39c0>                   

                             .py", line 1010, in run                            

                                 ->                                             

                                 self._target(*self._args,                      

                             <concurrent.futures.thread._WorkItem               

                             **self._kwargs)                                    

                             object at 0x7f9575287830>                          

                                 |    |        |    |        |                  

                               File                                             

                             -> {}                                              

                             "/usr/local/lib/python3.12/concurren               

                             t/futures/thread.py", line 58, in                  

                                 |    |        |    |        ->                 

                             <Thread(asyncio_0, started                         

                             run                                                

                                 result = self.fn(*self.args,                   

                             140277574489792)>                                  

                             **self.kwargs)                                     

                                 |    |        |    -> (<weakref                

                                          |    |   |    |       |               

                             at 0x7f9575296890; to                              

                             -> {}                                              

                             'ThreadPoolExecutor' at                            

                                          |    |   |    |                       

                             0x7f9575355b80>, <_queue.SimpleQueue               

                             ->                                                 

                             object at 0x7f9575296570>, None,...                

                             <concurrent.futures.thread._WorkItem               

                                 |    |        ->                               

                             object at 0x7f9575287830>                          

                             <Thread(asyncio_0, started                         

                                          |    |   |    -> ()                   

                             140277574489792)>                                  

                                          |    |   ->                           

                             <concurrent.futures.thread._WorkItem               

                                 |    -> <function _worker at                   

                             0x7f95029a3b00>                                    

                                 -> <Thread(asyncio_0, started                  

                             140277574489792)>                                  

                               File                                             

                             object at 0x7f9575287830>                          

                             "/usr/local/lib/python3.12/concurren               

                                          |    ->                               

                             t/futures/thread.py", line 92, in                  

                             _worker                                            

                             functools.partial(<built-in method                 

                                 work_item.run()                                

                             run of _contextvars.Context object                 

                                 |         -> <function                         

                             at 0x7f957526b780>, <bound method                  

                             DatabaseService._run_...                           

                                          ->                                    

                             <concurrent.futures.thread._WorkItem               

                             object at 0x7f9575287830>                          

                             > File                                             

                             "/app/.venv/lib/python3.12/site-pack               

                             ages/axiestudio/services/database/se               

                             rvice.py", line 355, in                            

                             _run_migrations                                    

                             ->                                                 

                             object at 0x7f9575296570>, None,...                

                             <concurrent.futures.thread._WorkItem               

                                 |    |        ->                               

                             object at 0x7f9575287830>                          

                             <Thread(asyncio_0, started                         

                                          |    |   |    -> ()                   

                             140277574489792)>                                  

                                          |    |   ->                           

                             <concurrent.futures.thread._WorkItem               

                                 |    -> <function _worker at                   

                             0x7f95029a3b00>                                    

                                 -> <Thread(asyncio_0, started                  

                             140277574489792)>                                  

                               File                                             

                             object at 0x7f9575287830>                          

                             "/usr/local/lib/python3.12/concurren               

                                          |    ->                               

                             t/futures/thread.py", line 92, in                  

                             _worker                                            

                             functools.partial(<built-in method                 

                                 work_item.run()                                

                             run of _contextvars.Context object                 

                                 |         -> <function                         

                             at 0x7f957526b780>, <bound method                  

                             DatabaseService._run_...                           

                                          ->                                    

                             <concurrent.futures.thread._WorkItem               

                             object at 0x7f9575287830>                          

                             > File                                             

                             "/app/.venv/lib/python3.12/site-pack               

                             ages/axiestudio/services/database/se               

                             rvice.py", line 355, in                            

                             _run_migrations                                    

                                 command.check(alembic_cfg)                     

                                 |       |     ->                               

                             <alembic.config.Config object at                   

                             0x7f95753c9d00>                                    

                                 |       -> <function check at                  

                             0x7f9507daee80>                                    

                                 -> <module 'alembic.command'                   

                             from                                               

                             '/app/.venv/lib/python3.12/site-pack               

                             ages/alembic/command.py'>                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-pack               

                             ages/alembic/command.py", line 373,                

                             in check                                           

                                 raise                                          

                             util.AutogenerateDiffsDetected(                    

                                       |    -> <class                           

                             'alembic.util.exc.AutogenerateDiffsD               

                             etected'>                                          

                                       -> <module 'alembic.util'                

                             from                                               

                             '/app/.venv/lib/python3.12/site-pack               

                             ages/alembic/util/__init__.py'>                    

                                                                                

                             alembic.util.exc.AutogenerateDiffsDe               

                             ('add_column', None, 'user',                       

                             tected: New upgrade operations                     

                             Column('failed_login_attempts',                    

                             detected: [('add_column', None,                    

                             Integer(), table=<user>,                           

                             'user', Column('login_attempts',                   

                             Integer(), table=<user>,                           

                             nullable=False,                                    

                             default=ScalarElementColumnDefault(0               

                             nullable=False,                                    

                             ))), ('add_column', None, 'user',                  

                             │   374 │   │   │   f"New upgrade  │               

                             default=ScalarElementColumnDefault(0               

                             Column('locked_until', DateTime(),                 

                             ))), ('add_column', None, 'user',                  

                             table=<user>)), ('add_column', None,               

                             │   375 │   │   │   revision_conte │               

                             Column('last_failed_login',                        

                             │                                  │               

                             'user', Column('last_login_ip',                    

                             │   371 │                          │               

                             DateTime(), table=<user>))]                        

                             AutoString(), table=<user>)),                      

                             │   376 │   │   │   diffs=diffs,   │               

                             ))), ('add_column', None, 'user',                  

                             Column('last_failed_login',                        

                                                                                

                             ('add_column', None, 'user',                       

                             │ /app/.venv/lib/python3.12/site-p │               

                             │   372 │   if diffs:              │               

                             Column('locked_until', DateTime(),                 

                             ╰──────────────────────────────────╯               

                             ╭─ Traceback (most recent call las─╮               

                             Column('password_changed_at',                      

                             DateTime(), table=<user>))]                        

                             │ ❱ 373 │   │   raise util.Autogen │               

                             │ ackages/alembic/command.py:373   │               

                             AutogenerateDiffsDetected: New                     

                             table=<user>)), ('add_column', None,               

                             │ /app/.venv/lib/python3.12/site-p │               

                             DateTime(), table=<user>)),                        

                             'user', Column('last_login_ip',                    

                             │ ackages/axiestudio/services/data │               

                             ('add_column', None, 'user',                       

                             │ in check                         │               

                             │ _run_migrations                  │               

                             upgrade operations detected:                       

                             AutoString(), table=<user>)),                      

                             │ base/service.py:355 in           │               

                             │                                  │               

                             │                                  │               

                             [('add_column', None, 'user',                      

                             Column('password_changed_at',                      

                             Column('login_attempts', Integer(),                

                             │   352 │   │   │                  │               

                             │   370 │   │   diffs.extend(upgra │               

                             DateTime(), table=<user>)),                        

                             │   353 │   │   │   try:           │               

                             table=<user>, nullable=False,                      

                             ('add_column', None, 'user',                       

                             │   354 │   │   │   │   buffer.wri │               

                             default=ScalarElementColumnDefault(0               

                             Column('failed_login_attempts',                    

                             │       migrations\n")             │               

                             Integer(), table=<user>,                           

                             │ ❱ 355 │   │   │   │   command.ch │               

                             nullable=False,                                    

                             │   356 │   │   │   except util.ex │               

                             default=ScalarElementColumnDefault(0               

                             │   357 │   │   │   │   logger.exc │               

                             ))), ('add_column', None, 'user',                  

                             │   358 │   │   │   │   if not fix │               


/ Launching Axie Studio...
- Launching Axie Studio...                    ERROR    2025-08-21 15:40:49 - ERROR    - utils  utils.py:59

                             - There's a mismatch between the models            

                             and the database.                                  

                             New upgrade operations detected:                   

                             [('add_column', None, 'user',                      

                             Column('login_attempts', Integer(),                

                             table=<user>, nullable=False,                      

                             default=ScalarElementColumnDefault(0)))            

                             , ('add_column', None, 'user',                     

                             Column('locked_until', DateTime(),                 

                             table=<user>)), ('add_column', None,               

                             'user', Column('last_login_ip',                    

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('password_changed_at',                      

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('failed_login_attempts',                    

                             Integer(), table=<user>,                           

                             nullable=False,                                    

                             default=ScalarElementColumnDefault(0)))            

                             , ('add_column', None, 'user',                     

                             Column('last_failed_login', DateTime(),            

                             table=<user>))]Traceback (most recent              

                             call last):                                        

                                                                                
                             s/alembic/command.py", line 373, in                

                             check                                              

                                 raise                                          

                             util.AutogenerateDiffsDetected(                    

                             Column('failed_login_attempts',                    

                             Integer(), table=<user>,                           

                                       |    -> <class                           

                             nullable=False,                                    

                             'alembic.util.exc.AutogenerateDiffsDete            

                             default=ScalarElementColumnDefault(0)))            

                             , ('add_column', None, 'user',                     

                             cted'>                                             

                                 app()                                          

                             Column('last_failed_login', DateTime(),            

                                       -> <module 'alembic.util'                

                             table=<user>))]                                    

                             from                                               

                                                                                

                                                                                

                             '/app/.venv/lib/python3.12/site-package            

                             The above exception was the direct                 

                             s/alembic/util/__init__.py'>                       

                             cause of the following exception:                  

                                                                                

                                                                                

                                                                                

                             alembic.util.exc.AutogenerateDiffsDetec            

                                                                                

                             Traceback (most recent call last):                 

                             ted: New upgrade operations detected:              

                                                                                

                             [('add_column', None, 'user',                      

                               File "/app/.venv/bin/axiestudio",                

                             Column('login_attempts', Integer(),                

                             line 10, in <module>                               

                             table=<user>, nullable=False,                      

                                 sys.exit(main())                               

                                 |   |    -> <function main at                  

                             default=ScalarElementColumnDefault(0)))            

                             0x7f957cee68e0>                                    

                             0x7f94678fc9a0>                                    

                                 |   -> <built-in function exit>                

                             , ('add_column', None, 'user',                     

                               File                                             

                                 -> <module 'sys' (built-in)>                   

                             Column('locked_until', DateTime(),                 

                             "/app/.venv/lib/python3.12/site-package            

                               File                                             

                             table=<user>)), ('add_column', None,               

                             s/axiestudio/__main__.py", line 834, in            

                             "/app/.venv/lib/python3.12/site-package            

                             'user', Column('last_login_ip',                    

                             main                                               

                             s/axiestudio/axiestudio_launcher.py",              

                             AutoString(), table=<user>)),                      

                             line 20, in main                                   

                             ('add_column', None, 'user',                       

                             Column('password_changed_at',                      

                                 -> <typer.main.Typer object at                 

                             DateTime(), table=<user>)),                        

                             0x7f9467aeabd0>                                    

                               File                                             

                             ('add_column', None, 'user',                       

                             "/app/.venv/lib/python3.12/site-package            

                             s/typer/main.py", line 324, in __call__            

                                 return get_command(self)(*args,                

                             **kwargs)                                          

                                        |           |      |                    

                             -> {}                                              

                                        |           |      -> ()                

                                        |           ->                          

                             <typer.main.Typer object at                        

                             0x7f9467aeabd0>                                    

                                        -> <function get_command at             

                                 axiestudio_main()                              

                             0x7f957c3468e0>                                    

                               File                                             

                                 -> <function main at                           

                             "/app/.venv/lib/python3.12/site-package            

                             s/click/core.py", line 1442, in                    

                             __call__                                           

                                 return self.main(*args, **kwargs)              

                                        |    |     |       -> {}                

                                        |    |     -> ()                        

                                        |    -> <function                       

                             TyperGroup.main at 0x7f957c345260>                 

                                        -> <TyperGroup >                        

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/typer/core.py", line 757, in main                

                                 return _main(                                  

                                        -> <function _main at                   

                             0x7f957c344360>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/typer/core.py", line 195, in _main               

                                 rv = self.invoke(ctx)                          

                                      |    |      ->                            

                             <click.core.Context object at                      

                             0x7f9467936900>                                    

                                      |    -> <function Group.invoke            

                             at 0x7f957cc76980>                                 

                                      -> <TyperGroup >                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/click/core.py", line 1830, in invoke             

                                 return                                         

                             _process_result(sub_ctx.command.invoke(            

                             sub_ctx))                                          

                                        |               |       |               

                             |      -> <click.core.Context object at            

                             0x7f94678c7650>                                    

                                        |               |       |               

                             -> <function Command.invoke at                     

                             0x7f957cc75760>                                    

                                        |               |       ->              

                             <TyperCommand run>                                 

                                        |               ->                      

                             <click.core.Context object at                      

                             0x7f94678c7650>                                    

                                        -> <function                            

                             Group.invoke.<locals>._process_result              

                             at 0x7f94678ff7e0>                                 

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/click/core.py", line 1226, in invoke             

                                 return ctx.invoke(self.callback,               

                             **ctx.params)                                      

                                        |   |      |    |                       

                             |   -> {'host': None, 'workers': None,             

                             'worker_timeout': None, 'port': None,              

                             'components_path':                                 

                             PosixPath('/app/.venv/lib/python3.12...            

                                        |   |      |    |                       

                             -> <click.core.Context object at                   

                             0x7f94678c7650>                                    

                                        |   |      |    -> <function            

                             run at 0x7f94678fccc0>                             

                                        |   |      -> <TyperCommand             

                             run>                                               

                                        |   -> <function                        

                             Context.invoke at 0x7f957cc749a0>                  

                                        -> <click.core.Context                  

                             object at 0x7f94678c7650>                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/click/core.py", line 794, in invoke              

                                 return callback(*args, **kwargs)               

                                        |         |       ->                    

                             {'host': None, 'workers': None,                    

                             'worker_timeout': None, 'port': None,              

                             'components_path':                                 

                             PosixPath('/app/.venv/lib/python3.12...            

                                        |         -> ()                         

                                        -> <function run at                     
                             object at 0x7f94e7f81070>                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/multiprocess/process.py", line 121,              

                             in start                                           

                                 self._popen = self._Popen(self)                

                                 |    |        |    |      ->                   

                             <Process name='Process-1' parent=1                 

                             started>                                           

                                 |    |        |    ->                          

                             <staticmethod(<function Process._Popen             

                             at 0x7f957b220220>)>                               

                                 |    |        -> <Process                      

                             name='Process-1' parent=1 started>                 

                                 |    -> None                                   

                                 -> <Process name='Process-1'                   

                             parent=1 started>                                  

                             child_r)                                           

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                                        |           |                           

                             s/multiprocess/context.py", line 224,              

                             -> 8                                               

                             in _Popen                                          

                                        |           -> <function                

                                 return                                         

                             BaseProcess._bootstrap at                          

                             _default_context.get_context().Process.            

                             0x7f957b3680e0>                                    

                             _Popen(process_obj)                                

                                        -> <Process name='Process-1'            

                                        |                |                      

                             parent=1 started>                                  

                             -> <Process name='Process-1' parent=1              

                             started>                                           

                                        |                ->                     

                             <function DefaultContext.get_context at            

                             0x7f957b220400>                                    

                                        ->                                      

                             <multiprocess.context.DefaultContext               

                             object at 0x7f957b35b350>                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/multiprocess/context.py", line 282,              

                             in _Popen                                          

                                 return Popen(process_obj)                      

                                        |     -> <Process                       

                             name='Process-1' parent=1 started>                 

                                        -> <class                               

                             'multiprocess.popen_fork.Popen'>                   

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/multiprocess/popen_fork.py", line 19,            

                             in __init__                                        

                                 self._launch(process_obj)                      

                                 |    |       -> <Process                       

                             name='Process-1' parent=1 started>                 

                                 |    -> <function Popen._launch at             

                             0x7f946642f7e0>                                    

                                 -> <multiprocess.popen_fork.Popen              

                             object at 0x7f9466403c80>                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/multiprocess/popen_fork.py", line 71,            

                             in _launch                                         

                                 code =                                         

                             process_obj._bootstrap(parent_sentinel=            

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/multiprocess/process.py", line 314,              

                             in _bootstrap                                      

                                 self.run()                                     

                                 |    -> <function BaseProcess.run              

                             at 0x7f957b347600>                                 

                                 -> <Process name='Process-1'                   

                             parent=1 started>                                  

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/multiprocess/process.py", line 108,              

                             in run                                             

                                 self._target(*self._args,                      

                             **self._kwargs)                                    

                                 |    |        |    |        |    ->            

 

                                 |    |        |    |        ->                 

                             <Process name='Process-1' parent=1                 

                             started>                                           

                                 |    |        |    -> ()                       

                                 |    |        -> <Process                      

                             name='Process-1' parent=1 started>                 

                                 |    -> <bound method                          

                             BaseApplication.run of                             

                             <axiestudio.server.AxieStudioApplicatio            

                             n object at 0x7f946665dc40>>                       

                                 -> <Process name='Process-1'                   

                             parent=1 started>                                  

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                                 self.manage_workers()                          

                             s/gunicorn/app/base.py", line 71, in               

                             run                                                

                             s/gunicorn/arbiter.py", line 570, in               

                                 Arbiter(self).run()                            

                                 |       ->                                     

                             manage_workers                                     

                                 |    -> <function                              

                                 self.spawn_workers()                           

                             <axiestudio.server.AxieStudioApplicatio            

                             Arbiter.spawn_workers at                           

                             Arbiter.manage_workers at                          

                                 |    -> <function                              

                             n object at 0x7f946665dc40>                        

                             0x7f94663bb560>                                    

                                 -> <class                                      

                                 -> <gunicorn.arbiter.Arbiter object            

                             0x7f94663bb420>                                    

                             s/gunicorn/arbiter.py", line 608, in               

                             'gunicorn.arbiter.Arbiter'>                        

                             <axiestudio.server.AxieStudioUvicornWor            

                                 -> <gunicorn.arbiter.Arbiter object            

                               File                                             

                             spawn_worker                                       

                             ker object at 0x7f94e6b9b320>                      

                             at 0x7f957b35ad80>                                 

                             at 0x7f957b35ad80>                                 

                             "/app/.venv/lib/python3.12/site-package            

                                 worker.init_process()                          

                               File                                             

                               File                                             

                               File                                             

                             s/gunicorn/arbiter.py", line 201, in               

                             "/app/.venv/lib/python3.12/site-package            

                             "/app/.venv/lib/python3.12/site-package            

                             "/app/.venv/lib/python3.12/site-package            

                             run                                                

                                 -> <gunicorn.arbiter.Arbiter object            

                             s/gunicorn/arbiter.py", line 641, in               

                             at 0x7f957b35ad80>                                 

                                 |      -> <function                            

                             spawn_workers                                      

                                        |       |   |    ->                     

                               File                                             

                                 ->                                             

                             UvicornWorker.init_process at                      

                             <function                                          

                                 self.spawn_worker()                            

                             "/app/.venv/lib/python3.12/site-package            

                             <axiestudio.server.AxieStudioUvicornWor            

                             0x7f94663f00e0>                                    

                             AxieStudioUvicornWorker._serve at                  

                                 |    -> <function                              

                             ker object at 0x7f94e6b9b320>         
                             running at                                         

                             BaseEventLoop._run_once at                         

                             0x7f957c079800>                                    

                             /app/.venv/lib/python3.12/site-packages            

                                 -> <_UnixSelectorEventLoop                     

                             /axiestu...                                        

                             running=True closed=False debug=False>             

                                        |    |     -> <function                 

                               File                                             

                             BaseEventLoop.run_until_complete at                

                             "/usr/local/lib/python3.12/asyncio/base            

                             0x7f957c0f7a60>                                    

                             _events.py", line 1987, in _run_once               

                                        |    ->                                 

                                 handle._run()                                  

                             <_UnixSelectorEventLoop running=True               

                                 |      -> <function Handle._run at             

                             closed=False debug=False>                          

                             0x7f957c211940>                                    

                                        -> <asyncio.runners.Runner              

                                 -> <Handle Task.task_wakeup(<Future            

                             object at 0x7f9466401640>                          

                             finis...e=<user>))]")>)>                           

                               File                                             

                               File                                             

                             "/usr/local/lib/python3.12/asyncio/base            

                             "/usr/local/lib/python3.12/asyncio/even            

                             ts.py", line 88, in _run                           

                                 self._context.run(self._callback,              

                             *self._args)                                       

                                 |    |            |    |                       

                             |    -> <member '_args' of 'Handle'                

                             objects>                                           

                                 |    |            |    |                       

                             -> <Handle Task.task_wakeup(<Future                

                             finis...e=<user>))]")>)>                           

                                 |    |            |    -> <member              

                             '_callback' of 'Handle' objects>                   

                                 |    |            -> <Handle                   

                             Task.task_wakeup(<Future                           

                             finis...e=<user>))]")>)>                           

                                 |    -> <member '_context' of                  

                             'Handle' objects>                                  

                                 -> <Handle Task.task_wakeup(<Future            

                             finis...e=<user>))]")>)>                           

                               File                                             

                             at 0x7f946641d3d0>>                                

                                 await                                          

                             Integer(), table=<user>,                           


\ Launching Axie Studio...
| Launching Axie Studio...                    ERROR    2025-08-21 15:40:49 - ERROR    - main - main.py:236

                             There's a mismatch between the models              

                             and the database.                                  

                             New upgrade operations detected:                   

                             [('add_column', None, 'user',                      

                             Column('login_attempts', Integer(),                

                             table=<user>, nullable=False,                      

                             default=ScalarElementColumnDefault(0)))            

                             , ('add_column', None, 'user',                     

                             Column('locked_until', DateTime(),                 

                             table=<user>)), ('add_column', None,               

                             'user', Column('last_login_ip',                    

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('password_changed_at',                      

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('failed_login_attempts',                    

                             Integer(), table=<user>,                           

                             nullable=False,                                    

                             default=ScalarElementColumnDefault(0)))            

                             , ('add_column', None, 'user',                     

                             Column('last_failed_login', DateTime(),            

                             table=<user>))]Traceback (most recent              

                             call last):                                        

                                                                                

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/services/database/service.            

                             py", line 355, in _run_migrations                  

                                 command.check(alembic_cfg)                     

                                 |       |     ->                               

                             <alembic.config.Config object at                   

                             0x7f95753c9d00>                                    

                                 |       -> <function check at                  

                             0x7f9507daee80>                                    

                                 -> <module 'alembic.command' from              

                             '/app/.venv/lib/python3.12/site-package            

                             s/alembic/command.py'>                             

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/alembic/command.py", line 373, in                

                             check                                              

                                 raise                                          

                             util.AutogenerateDiffsDetected(                    

                                       |    -> <class                           

                             'alembic.util.exc.AutogenerateDiffsDete            

                             cted'>                                             

                                       -> <module 'alembic.util'                

                             from                                               

                             '/app/.venv/lib/python3.12/site-package            

                             s/alembic/util/__init__.py'>                       

                                                                                

                             alembic.util.exc.AutogenerateDiffsDetec            

                             ted: New upgrade operations detected:              

                             [('add_column', None, 'user',                      

                             Column('login_attempts', Integer(),                

                             table=<user>, nullable=False,                      

                             default=ScalarElementColumnDefault(0)))            

                             , ('add_column', None, 'user',                     

                             Column('locked_until', DateTime(),                 

                             table=<user>)), ('add_column', None,               

                             'user', Column('last_login_ip',                    

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('password_changed_at',                      

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('failed_login_attempts',                    

                             Integer(), table=<user>,                           

                             nullable=False,                                    

                             default=ScalarElementColumnDefault(0)))            

                             , ('add_column', None, 'user',                     

                             Column('last_failed_login', DateTime(),            

                             table=<user>))]                                    

                                                                                

                                                                                

                             The above exception was the direct                 

                             cause of the following exception:                  

                                                                 
                             0x7f9467936900>                                    

                             TyperGroup.main at 0x7f957c345260>                 

                                      |    -> <function Group.invoke            

                                 return _main(                                  

                                        -> <TyperGroup >                        

                                        -> <function _main at                   

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             0x7f957c344360>                                    

                               File                                             

                             s/typer/core.py", line 757, in main                

                             "/app/.venv/lib/python3.12/site-package            

                             s/typer/core.py", line 195, in _main               

                                 rv = self.invoke(ctx)                          

                                      |    |      ->                            

                                 |    |        |    |        ->                 

                                 await app(scope, self.receive,                 

                               File                                             

                                            ->                                  

                                              |    |                            

                             │   230 │   async with db_service.wit │            


/ Launching Axie Studio...
+ Stopping Server (0.10s)


\ Cancelling Background Tasks...
- Launching Axie Studio...
+ Cancelling Background Tasks


| Cleaning Up Services...                    DEBUG    2025-08-21 15:40:50 - DEBUG    - utils utils.py:104

                             - AUTO_LOGIN is set to False. Removing             

                             default superuser if exists.                       


\ Launching Axie Studio...
/ Cleaning Up Services...
| Launching Axie Studio...
- Cleaning Up Services...
/ Launching Axie Studio...
\ Cleaning Up Services...
- Launching Axie Studio...
| Cleaning Up Services...
\ Launching Axie Studio...
/ Cleaning Up Services...


| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
- Cleaning Up Services...
\ Launching Axie Studio...
\ Cleaning Up Services...
| Launching Axie Studio...
/ Launching Axie Studio...
| Cleaning Up Services...
- Launching Axie Studio...


/ Cleaning Up Services...
\ Launching Axie Studio...
- Cleaning Up Services...
| Launching Axie Studio...
\ Cleaning Up Services...
/ Launching Axie Studio...
| Cleaning Up Services...                    ERROR    2025-08-21 15:40:50 - ERROR    - utils utils.py:119

                             - (psycopg.errors.UndefinedColumn)                 

                             column user.login_attempts does not                

                             exist                                              

                             LINE 1: ...ication_token,                          

                             "user".email_verification_expires,                 

                             "user".log...                                      

                                                                                

                                                    ^                           

                             [SQL: SELECT "user".id,                            

                             "user".username, "user".email,                     

                             "user".password, "user".profile_image,             

                             "user".is_active, "user".is_superuser,             

                             "user".create_at, "user".updated_at,               

                             "user".last_login_at,                              

                             "user".signup_ip,                                  

                             "user".device_fingerprint,                         

                             "user".email_verified,                             

                             "user".email_verification_token,                   

                             "user".email_verification_expires,                 

                             "user".login_attempts,                             

                             "user".locked_until,                               

                             "user".last_login_ip,                              

                             "user".password_changed_at,                        

                             "user".failed_login_attempts,                      

                             "user".last_failed_login,                          

                             "user".stripe_customer_id,                         

                             "user".subscription_status,                        

                             "user".subscription_id,                            

                             "user".trial_start, "user".trial_end,              

                             "user".subscription_start,                         

                             "user".subscription_end,                           

                             "user".store_api_key, "user".optins                

                             FROM "user"                                        

                             WHERE "user".username =                            

                             %(username_1)s::VARCHAR]                           

                                                                                

                             (Background on this error at:                      

                             https://sqlalche.me/e/20/f405)Tracebac             

                             k (most recent call last):                         

                                                                                

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/services/database/servic             

                             e.py", line 355, in _run_migrations                

                                 command.check(alembic_cfg)                     

                                 |       |     ->                               

                             <alembic.config.Config object at                   

                             0x7f95753c9d00>                                    

                                 |       -> <function check at                  

                             0x7f9507daee80>                                    

                                 -> <module 'alembic.command' from              

                             '/app/.venv/lib/python3.12/site-packag             

                             es/alembic/command.py'>                            

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/alembic/command.py", line 373, in               

                             check                                              

                                 raise                                          

                             util.AutogenerateDiffsDetected(                    

                                       |    -> <class                           

                             'alembic.util.exc.AutogenerateDiffsDet             

                             ected'>                                            

                                       -> <module 'alembic.util'                

                             from                                               

                             '/app/.venv/lib/python3.12/site-packag             

                             es/alembic/util/__init__.py'>                      

                                                                                

                             alembic.util.exc.AutogenerateDiffsDete             

                             cted: New upgrade operations detected:             

                             [('add_column', None, 'user',                      

                             Column('login_attempts', Integer(),                

                             table=<user>, nullable=False,                      

                             default=ScalarElementColumnDefault(0))             

                             ), ('add_column', None, 'user',                    

                             Column('locked_until', DateTime(),                 

                             table=<user>)), ('add_column', None,               

                             'user', Column('last_login_ip',                    

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('password_changed_at',                      

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('failed_login_attempts',                    

                             Integer(), table=<user>,                           

                             nullable=False,                                    

                             default=ScalarElementColumnDefault(0))             

                             ), ('add_column', None, 'user',                    

                             Column('last_failed_login',                        

                             DateTime(), table=<user>))]                        

                                                                                

                                                                                

                             The above exception was the direct                 

                             cause of the following exception:                  

                                                                       
                             DatabaseService object at                          

                             0x7f94679340e0>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/services/database/servic             

                             e.py", line 375, in run_migrations                 

                                 await                                          

                             asyncio.to_thread(self._run_migrations             

                             , should_initialize_alembic, fix)                  

                                       |       |         |    |                 

                             |                          -> False                

                                       |       |         |    |                 

                             -> False                                           

                                       |       |         |    ->                

                             <function                                          

                             DatabaseService._run_migrations at                 

                             0x7f950298e340>                                    

                                       |       |         ->                     

                             <axiestudio.services.database.service.             

                             DatabaseService object at                          

                             0x7f94679340e0>                                    

                                       |       -> <function                     

                             to_thread at 0x7f957c0b6980>                       

                                       -> <module 'asyncio' from                

                             '/usr/local/lib/python3.12/asyncio/__i             

                             nit__.py'>                                         

                               File                                             

                             "/usr/local/lib/python3.12/asyncio/thr             

                             eads.py", line 25, in to_thread                    

                                 return await                                   

                             loop.run_in_executor(None, func_call)              

                                              |    |                            

                             -> functools.partial(<built-in method              

                             run of _contextvars.Context object at              

                             0x7f957526b780>, <bound method                     

                             DatabaseService._run_...                           

                                              |    -> <function                 

                             BaseEventLoop.run_in_executor at                   

                             0x7f957c078360>                                    

                                              ->                                

                             <_UnixSelectorEventLoop running=True               

                             closed=False debug=False>                          

                               File                                             

                             "/usr/local/lib/python3.12/concurrent/             

                             futures/thread.py", line 58, in run                

                                 result = self.fn(*self.args,                   

                             **self.kwargs)                                     

                                          |        |            ->              

                             None                                               

                                          |        -> None                      

                                          -> None                               

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/services/database/servic             

                             e.py", line 360, in _run_migrations                

                                 raise RuntimeError(msg) from exc               

                                                    |         ->                

                             between the models and the database.               

                             New upgrade operations detected:                   

                             [('add_column', None, 'user',                      

                             Column('login_attempts', Integer(),                

                             table=<user>, nullable=False,                      

                             default=ScalarElementColumnDefault(0))             

                             ), ('add_column', None, 'user',                    

                             Column('locked_until', DateTime(),                 

                             table=<user>)), ('add_column', None,               

                             'user', Column('last_login_ip',                    

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('password_changed_at',                      

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('failed_login_attempts',                    

                             Integer(), table=<user>,                           

                             nullable=False,                                    

                             default=ScalarElementColumnDefault(0))             

                             ), ('add_column', None, 'user',                    

                             Column('last_failed_login',                        

                             DateTime(), table=<user>))]                        

                                                                                

                                                                                

                             During handling of the above                       

                             exception, another exception occurred:             

                                                                                

                                                                                

                             Traceback (most recent call last):                 

                                                                                

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             0x7f9575194a40>                                    

                             g.PGDialectAsync_psycopg object at                 

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/sqlalchemy/engine/base.py", line                

                             0x7f946646fef0>                                    

                             es/sqlalchemy/util/_concurrency_py3k.p             

                                 value = await result                           

                               File                                             

                             y", line 132, in await_only                        

                             1963, in _exec_single_context                      

                                 ->                                             

                                               -> <coroutine object             

                                 return                                         

                             "/app/.venv/lib/python3.12/site-packag             

                             <sqlalchemy.engine.base.Connection                 

                                 self.dialect.do_execute(                       

                             AsyncCursor.execute at 0x7f9574fb96c0>             

                             current.parent.switch(awaitable)  #                

                             es/psycopg/cursor_async.py", line 97,              

                             object at 0x7f9574ae2a50>                          

                                 |    |       -> <function                      

                             type: ignore # noqa: E501                          

                               File                                             

                             DefaultDialect.do_execute at                       

                             (otid=0x7f957b2c5230) dead>                        

                             in execute                                         

                                        |       |             ->                

                             "/app/.venv/lib/python3.12/site-packag             

                             0x7f957a978cc0>                                    

                             <coroutine object AsyncCursor.execute              

                             Traceback (most recent call last):                 

                               File                                             

                                 |    ->                                        

                             es/sqlalchemy/engine/default.py", line             

                             at 0x7f9574fb96c0>                                 

                             "/app/.venv/lib/python3.12/site-packag             

                                 raise ex.with_traceback(None)                  

                             <sqlalchemy.dialects.postgresql.psycop             

                             943, in do_execute                                 

                                        |       -> <attribute                   

                             es/sqlalchemy/util/_concurrency_py3k.p             

                             'parent' of 'greenlet.greenlet'                    

                                                                                

                                 cursor.execute(statement,                      

                             y", line 196, in greenlet_spawn                    

                             objects>                                           

                             parameters)                                        

                             psycopg.errors.UndefinedColumn: column             

                                        -> <_AsyncIoGreenlet object             

                                 |      |       |          ->                   

                             at 0x7f9575194d40                                  

                             user.login_attempts does not exist                 

                             {'username_1': 'axiestudio'}                       

                             LINE 1: ...ication_token,                          

                                 |      |       -> 'SELECT                      

                             "user".email_verification_expires,                 

                             "user".id, "user".username,                        

                             "user".email, "user".password,                     

                             "user".log...                                      

                             "user".profile_image,                              

                                                                                

                             "user".is_active,                                  

                                                    ^             
                              line 20, in main                                  

                             <function run at 0x7f94678fccc0>                   

                               File                                             

                             rt()                                               

                                 axiestudio_main()                              

                             "/app/.venv/lib/python3.12/site-packag             

                                 |               |              ->              

                                 -> <function main at                           

                             es/typer/main.py", line 699, in                    

                             0x7f94678fc9a0>                                    

                             wrapper                                            

                               File                                             

                                        |   |      -> <TyperCommand             

                                 return callback(**use_params)                  

                             "/app/.venv/lib/python3.12/site-packag             

                                        |          -> {'host':                  

                             es/axiestudio/__main__.py", line 834,              

                             run>                                               

                             None, 'workers': None,                             

                             in main                                            

                                        |   -> <function                        

                             'worker_timeout': None, 'port': None,              

                                 app()                                          

                             Context.invoke at 0x7f957cc749a0>                  

                             <function BaseProcess.start at                     

                             'components_path':                                 

                                        -> <click.core.Context                  

                                 -> <typer.main.Typer object at                 

                             PosixPath('/app/.venv/lib/python3.12..             

                             0x7f957b3476a0>                                    

                             0x7f9467aeabd0>                                    

                             object at 0x7f94678c7650>                          

                               File                                             

                                 |               -> <Process                    

                               File                                             

                             .                                                  

                             "/app/.venv/lib/python3.12/site-packag             

                             name='Process-1' parent=1 started>                 

                             es/typer/main.py", line 324, in                    

                             "/app/.venv/lib/python3.12/site-packag             

                                        -> <function run at                     

                                 ->                                             

                             __call__                                           

                             es/click/core.py", line 794, in invoke             

                                 return get_command(self)(*args,                

                             0x7f9467991e40>                                    

                             <axiestudio.__main__.ProcessManager                

                             **kwargs)                                          

                               File                                             

                                 return callback(*args, **kwargs)               

                                        |           |      |                    

                             -> {}                                              

                               File                                             

                                        |         |       ->                    

                                        |           |      -> ()                

                                        |           ->                          

                             {'host': None, 'workers': None,                    

                             "/app/.venv/lib/python3.12/site-packag             

                             <typer.main.Typer object at                        

                             0x7f9467aeabd0>                                    

                             'worker_timeout': None, 'port': None,              

                             es/multiprocess/process.py", line 121,             

                                        -> <function get_command at             

                             'components_path':                                 

                             0x7f957c3468e0>                                    

                             in start                                           

                               File                                             

                                 self._popen = self._Popen(self)                

                             "/app/.venv/lib/python3.12/site-packag             

                                 |    |        |    |      ->                   

                             es/click/core.py", line 1442, in                   

                             <Process name='Process-1' parent=1                 

                             __call__                                           

                             started>                                           

                                 |    |        -> <Process                      

                                 return self.main(*args, **kwargs)              

                                 |    |        |    ->                          

                                        |    |     |       -> {}                

                             name='Process-1' parent=1 started>                 

                             <staticmethod(<function Process._Popen             

                                        |    |     -> ()                        

                                 |    -> None                                   

                             at 0x7f957b220220>)>                               

                                        |    -> <function                       

                             TyperGroup.main at 0x7f957c345260>                 

                                        -> <TyperGroup >                        

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/typer/core.py", line 757, in main               

                                 return _main(                                  

                                        -> <function _main at                   

                             0x7f957c344360>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/typer/core.py", line 195, in _main              

                                 rv = self.invoke(ctx)                          

                                      |    |      ->                            

                             <click.core.Context object at                      

                             0x7f9467936900>                                    

                                      |    -> <function                         

                             Group.invoke at 0x7f957cc76980>                    

                                      -> <TyperGroup >                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/click/core.py", line 1830, in                   

                             invoke                                             

                                 return                                         

                             _process_result(sub_ctx.command.invoke             

                             (sub_ctx))                                         

                                        |               |       |               

                             |      -> <click.core.Context object               

                             at 0x7f94678c7650>                                 

                                        |               |       |               

                             -> <function Command.invoke at                     

                             0x7f957cc75760>                                    

                                        |               |       ->              

                             <TyperCommand run>                                 

                                        |               ->                      

                             <click.core.Context object at                      

                             0x7f94678c7650>                                    

                                        -> <function                            

                             Group.invoke.<locals>._process_result              

                             at 0x7f94678ff7e0>                                 

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/click/core.py", line 1226, in                   

                             invoke                                             

                                 return ctx.invoke(self.callback,               

                             **ctx.params)                                      

                                        |   |      |    |                       

                             "/app/.venv/lib/python3.12/site-packag             

                             'Handle' objects>                                  

                               File                                             

                             'app': <fastapi.applications.FastAPI               

                               File                                             

                             DefaultDialect.do_execute at                       

                             │   370 │   │   diffs.extend(upgrade │             

                             │       # noqa: E501                 │             

                             │    941 │                           │       
                             <axiestudio.services.database.service.D            

                             Traceback (most recent call last):                 

                             0x7f957c078360>                                    

                                                                                

                             atabaseService object at                           

                                              ->                                

                               File                                             

                             <_UnixSelectorEventLoop running=True               

                             0x7f94679340e0>                                    

                             "/app/.venv/lib/python3.12/site-package            

                                       |       -> <function                     

                             s/axiestudio/main.py", line 146, in                

                             closed=False debug=False>                          

                             to_thread at 0x7f957c0b6980>                       

                             lifespan                                           

                               File                                             

                                       -> <module 'asyncio' from                

                                 result = self.fn(*self.args,                   

                                 await                                          

                             **self.kwargs)                                     

                             initialize_services(fix_migration=fix_m            

                             igration)                                          

                                          |        |            ->              

                             None                                               

                                       |                                        

                                          |        -> None                      

                             -> False                                           

                                          -> None                               

                                       -> <function                             

                               File                                             

                             initialize_services at 0x7f950298d800>             

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/services/database/service.            

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             py", line 360, in _run_migrations                  

                             s/axiestudio/services/utils.py", line              

                                 raise RuntimeError(msg) from exc               

                             227, in initialize_services                        

                                                    |         ->                

                                 await                                          

                             <module 'sqlalchemy.exc' from                      

                             initialize_database(fix_migration=fix_m            

                             '/app/.venv/lib/python3.12/site-package            

                             igration)                                          

                             s/sqlalchemy/exc.py'>                              

                                       |                                        

                                                    -> "There's a               

                             -> False                                           

                                       -> <function                             

                             initialize_database at 0x7f94e9fa68e0>             

                             mismatch between the models and the                

                               File                                             

                             database.\nNew upgrade operations                  

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/services/database/utils.py            

                             detected: [('add_column', None, 'user',            

                             DatabaseService.run_migrations at                  

                             ", line 40, in initialize_database                 

                             Colu...                                            

                                                                                

                                 await                                          

                             0x7f950298e3e0>                                    

                                 await                                          

                             RuntimeError: There's a mismatch                   

                                       ->                                       

                             asyncio.to_thread(self._run_migrations,            

                             between the models and the database.               

                             database_service.run_migrations(fix=fix            

                             <axiestudio.services.database.service.D            

                             New upgrade operations detected:                   

                             _migration)                                        

                             atabaseService object at                           

                             should_initialize_alembic, fix)                    

                             [('add_column', None, 'user',                      

                                       |                |                       

                             0x7f94679340e0>                                    

                             Column('login_attempts', Integer(),                

                             -> False                                           

                               File                                             

                                       |       |         |    |                 

                                       |                -> <function            

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/services/database/service.            

                             py", line 375, in run_migrations                   

                             table=<user>, nullable=False,                      

                             default=ScalarElementColumnDefault(0)))            

                             , ('add_column', None, 'user',                     

                             Column('locked_until', DateTime(),                 

                             table=<user>)), ('add_column', None,               

                             'user', Column('last_login_ip',                    

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('password_changed_at',                      

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('failed_login_attempts',                    

                             Integer(), table=<user>,                           

                             nullable=False,                                    

                             default=ScalarElementColumnDefault(0)))            

                             , ('add_column', None, 'user',                     

                             Column('last_failed_login', DateTime(),            

                             table=<user>))]                                    

                                                                                

                                                                                

                             During handling of the above exception,            

                             another exception occurred:                        

                                                                                

                                                                                

                             Traceback (most recent call last):                 

                                                                                

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/sqlalchemy/engine/base.py", line                 

                             1963, in _exec_single_context                      

                                 self.dialect.do_execute(                       

                                 |    |       -> <function                      

                             DefaultDialect.do_execute at                       

                             0x7f957a978cc0>                                    

                                 |    ->                                        

                             <sqlalchemy.dialects.postgresql.psycopg            

                             .PGDialectAsync_psycopg object at                  

                             0x7f946646fef0>                                    

                                 ->                                             

                             <sqlalchemy.engine.base.Connection                 

                             object at 0x7f9574ae2a50>                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/sqlalchemy/engine/default.py", line              

                             943, in do_execute                                 

                                 cursor.execute(statement,                      

                             parameters)                                        


                             {'username_1': 'axiestudio'}                       

                                 |      |       -> 'SELECT                      

                             "user".id, "user".username,                        

                             "user".email, "user".password,                     

                             "user".profile_image, "user".is_active,            

                             "user".is_superuse...                              

                                 |      -> <function                            

                             AsyncAdapt_psycopg_cursor.execute at               

                             0x7f950afe19e0>                                    

                                 ->                                             

                             <sqlalchemy.dialects.postgresql.psycopg            

                             .AsyncAdapt_psycopg_cursor object at               

                             0x7f9575194a40>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/sqlalchemy/dialects/postgresql/psycop            

                             g.py", line 594, in execute                        

                                 result =                                       

                             self.await_(self._cursor.execute(query,            

                             params, **kw))                                     

                                          |    |      |    |                    

                             |      |         -> {}                             

                                          |    |      |    |                    

                             |      -> {'username_1': 'axiestudio'}             

                                          |    |      |    |                    

                             -> 'SELECT "user".id, "user".username,             

                             "user".email, "user".password,                     

                             "user".profile_image, "user".is_active,            

                             "user".is_superuse...                              

                                          |    |      |    ->                   

                             <member '_cursor' of                               

                             'AsyncAdapt_psycopg_cursor' objects>               

                                          |    |      ->                        

                             <sqlalchemy.dialects.postgresql.psycopg            

                             .AsyncAdapt_psycopg_cursor object at               

                             0x7f9575194a40>                                    

                                          |    -> <member 'await_'              

                             of 'AsyncAdapt_psycopg_cursor' objects>            

                                          ->                                    

                             <sqlalchemy.dialects.postgresql.psycopg            

                             .AsyncAdapt_psycopg_cursor object at               

                             0x7f9575194a40>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/sqlalchemy/util/_concurrency_py3k.py"            

                             , line 132, in await_only                          

                             <coroutine object AsyncCursor.execute              

                                 return                                         

                             at 0x7f9574fb96c0>                                 

                             current.parent.switch(awaitable)  #                

                                        |       -> <attribute                   

                             'parent' of 'greenlet.greenlet'                    

                             type: ignore # noqa: E501                          

                             objects>                                           

                                        -> <_AsyncIoGreenlet object             

                                        |       |             ->                

                             at 0x7f9575194d40 (otid=0x7f957b2c5230)            

                             dead>                                              

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/sqlalchemy/util/_concurrency_py3k.py"            

                             , line 196, in greenlet_spawn                      


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...

Railway rate limit of 500 logs/sec reached for replica, update your application to reduce the logging rate. Messages dropped: 4937


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axi
