                  logger - Cache directory:                          

                             /app/data/.cache/axiestudio                        

                    DEBUG    2025-08-18 22:52:24 - DEBUG    -      logger.py:233

                             logger - Log file:                                 

                             /app/data/.cache/axiestudio/axiestudi              

                             o.log                                              

                    DEBUG    2025-08-18 22:52:24 - DEBUG    -      logger.py:255

                             logger - Logger set up with log                    

                             level: debug                                       


- Initializing Axie Studio...                    DEBUG    2025-08-18 22:52:24 - DEBUG    -    __main__.py:273

                             __main__ - No env_file provided.                   

                    DEBUG    2025-08-18 22:52:24 - DEBUG    -      manager.py:55

                             manager - Create service                           

                             ServiceType.SETTINGS_SERVICE                       

                    DEBUG    2025-08-18 22:52:24 - DEBUG    - base - base.py:357

                             No database_url provided, trying                   

                             AXIESTUDIO_DATABASE_URL env variable               

                    DEBUG    2025-08-18 22:52:24 - DEBUG    - base - base.py:360

                             Using AXIESTUDIO_DATABASE_URL env                  

                             variable.                                          

                    DEBUG    2025-08-18 22:52:24 - DEBUG    - base - base.py:456

                             Setting default components path to                 

                             components_path                                    

                    DEBUG    2025-08-18 22:52:24 - DEBUG    - base - base.py:464

                             Components path:                                   

                             ['/app/.venv/lib/python3.12/site-packag            

                             es/axiestudio/components']                         

                    DEBUG    2025-08-18 22:52:24 - DEBUG    - base - base.py:309

                             Setting user agent to axiestudio                   

[08/18/25 22:52:25] DEBUG    2025-08-18 22:52:25 - DEBUG    - auth -  auth.py:95

                             Secret key provided                                


+ Initializing Axie Studio


\ Checking Environment...                    DEBUG    2025-08-18 22:52:25 - DEBUG    - auth -  auth.py:95

                             Secret key provided                                

                    DEBUG    2025-08-18 22:52:25 - DEBUG    - base - base.py:475

                             Updating settings                                  

                    DEBUG    2025-08-18 22:52:25 - DEBUG    - base - base.py:481

                             Updating components_path                           

                    DEBUG    2025-08-18 22:52:25 - DEBUG    - base - base.py:502

                             components_path:                                   

                             ['/app/.venv/lib/python3.12/site-packag            

                             es/axiestudio/components']                         

                    DEBUG    2025-08-18 22:52:25 - DEBUG    -    __main__.py:298

                             __main__ - Loading config from cli                 

                             parameter 'components_path':                       

                             '/app/.venv/lib/python3.12/site-pac                

                             kages/axiestudio/components'                       


+ Checking Environment

 Starting Core Services...[08/18/25 22:52:25] DEBUG    2025-08-18 22:52:25 - DEBUG    -      logger.py:231

                             logger - Cache directory:                          

                             /app/data/.cache/axiestudio                        

                    DEBUG    2025-08-18 22:52:25 - DEBUG    -      logger.py:233

                             logger - Log file:                                 

                             /app/data/.cache/axiestudio/axiestudi              

                             o.log                                              

                    DEBUG    2025-08-18 22:52:25 - DEBUG    -      logger.py:255

                             logger - Logger set up with log                    

                             level: debug                                       

                    DEBUG    2025-08-18 22:52:25 - DEBUG    -      manager.py:55

                             manager - Create service                           

                             ServiceType.TELEMETRY_SERVICE                      


/ Starting Core Services...
+ Starting Core Services


- Connecting Database...
+ Connecting Database


\ Loading Components...
+ Loading Components


| Adding Starter Projects...
+ Adding Starter Projects


/ Launching Axie Studio...[08/18/25 22:52:26] DEBUG    2025-08-18 22:52:26 - DEBUG    -    __main__.py:111

                             __main__ - Number of workers: 1                    

[08/18/25 22:52:26] DEBUG    2025-08-18 22:52:26 - DEBUG    -      logger.py:231

                             logger - Cache directory:                          

                             /app/data/.cache/axiestudio                        

                    DEBUG    2025-08-18 22:52:26 - DEBUG    -      logger.py:233

                             logger - Log file:                                 

                             /app/data/.cache/axiestudio/axiestudi              

                             o.log                                              

                    DEBUG    2025-08-18 22:52:26 - DEBUG    -      logger.py:255

                             logger - Logger set up with log                    

                             level: debug                                       

                    DEBUG    2025-08-18 22:52:26 - DEBUG    - main - main.py:135

                             Starting Axie Studio v1.5.0.post1...               

                    DEBUG    2025-08-18 22:52:26 - DEBUG    - main - main.py:145

                             Initializing services                              

                    DEBUG    2025-08-18 22:52:26 - DEBUG    -      manager.py:55

                             manager - Create service                           

                             ServiceType.CACHE_SERVICE                          

                    DEBUG    2025-08-18 22:52:26 - DEBUG    - utils  utils.py:17

                             - Initializing database                            

                    DEBUG    2025-08-18 22:52:26 - DEBUG    -      manager.py:55

                             manager - Create service                           

                             ServiceType.DATABASE_SERVICE                       


- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...[08/18/25 22:52:27] DEBUG    2025-08-18 22:52:27 - DEBUG    -     service.py:438

                             service - Database and tables                      

                             already exist                                      


- Launching Axie Studio...
\ Launching Axie Studio...                    DEBUG    2025-08-18 22:52:27 - DEBUG    -     service.py:298

                             service - Missing column: email in                 

                             table user                                         


| Launching Axie Studio...                    DEBUG    2025-08-18 22:52:27 - DEBUG    -     service.py:342

                             service - Alembic initialized                      


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...[08/18/25 22:52:28] DEBUG    2025-08-18 22:52:28 - DEBUG    -     service.py:348

                             service - Error checking migrations:               

                             Target database is not up to date.                 


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...


/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...


\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...Email and subscription fields are handled by separate migrations - skipping

Added signup_ip column

Created signup_ip index

                             <Thread(asyncio_0, started                         

                                 -> <Thread(asyncio_0, started                  

                             **self._kwargs)                                    

                             <concurrent.futures.thread._WorkItem               

                             140434391119552)>                                  

                             140434391119552)>                                  

                             object at 0x7fb9f9788a40>                          

                                 |    |        |    -> (<weakref                

                               File                                             

                             _worker                                            

                             at 0x7fb9f8c5e6b0; to                              

                             "/usr/local/lib/python3.12/concurren               

                             140434391119552)>                                  

                                 work_item.run()                                

                             -> {}                                              

                                 |    -> <function _worker at                   

                             t/futures/thread.py", line 92, in                  

                                 |         -> <function                         

                                          |    |   |    |                       

                             0x7fb98b983a60>                                    

                             object at 0x7fb9f9788a40>                          

                                          |    ->                               

                             _WorkItem.run at 0x7fb98b983920>                   

                                          |    |   |    -> ()                   

                                          |    |   ->                           

                               File                                             

                             functools.partial(<built-in method                 

                             ->                                                 

                             "/usr/local/lib/python3.12/concurren               

                             <concurrent.futures.thread._WorkItem               

                             object at 0x7fb9f9788a40>                          

                             0x7fb8e9ede2d0>                                    

                             <concurrent.futures.thread._WorkItem               

                             object at 0x7fb9f9788a40>                          

                             t/futures/thread.py", line 58, in                  

                             > File                                             

                             run of _contextvars.Context object                 

                                 |       -> <function check at                  

                                 result = self.fn(*self.args,                   

                             run                                                

                                          ->                                    

                             0x7fb992d8ede0>                                    

                             at 0x7fb9f8db4200>, <bound method                  

                             "/app/.venv/lib/python3.12/site-pack               

                                 -> <module 'alembic.command'                   

                             <concurrent.futures.thread._WorkItem               

                             **self.kwargs)                                     

                             DatabaseService._run_...                           

                             ages/axiestudio/services/database/se               

                             ages/alembic/command.py'>                          

                             from                                               

                                          |    |   |    |       |               

                             rvice.py", line 355, in                            

                               File                                             

                             '/app/.venv/lib/python3.12/site-pack               

                             _run_migrations                                    

                             "/app/.venv/lib/python3.12/site-pack               

                                 command.check(alembic_cfg)                     

                             ages/alembic/command.py", line 373,                

                                 |       |     ->                               

                             <alembic.config.Config object at                   

                             in check                                           

                                 raise                                          

                             util.AutogenerateDiffsDetected(                    

                                       |    -> <class                           

                             'alembic.util.exc.AutogenerateDiffsD               

                             etected'>                                          

                                       -> <module 'alembic.util'                

                             from                              

      '/app/.venv/lib/python3.12/site-pack               

                             ages/alembic/util/__init__.py'>                    

                                                                                

                             Column('email', AutoString(),                      

                             alembic.util.exc.AutogenerateDiffsDe               

                             table=<user>)))]                                   

                             tected: New upgrade operations                     

                             detected: [('add_column', None,                    

                             'user', Column('email',                            

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('stripe_customer_id',                       

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('subscription_status',                      

                             AutoString(), table=<user>,                        

                             default=ScalarElementColumnDefault('               

                             trial'))), ('add_column', None,                    

                             'user', Column('subscription_id',                  

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('trial_start', DateTime(),                  

                             table=<user>,                                      

                             default=CallableColumnDefault(<funct               

                             ion User.<lambda> at                               

                             0x7fb9780cca40>))), ('add_column',                 

                             None, 'user', Column('trial_end',                  

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('subscription_start',                       

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('subscription_end',                         

                             DateTime(), table=<user>)),                        

                             ('add_index', Index('ix_user_email',               

                             Column('email', AutoString(),                      

                             table=<user>)))]                                   

                                                                                

                             ╭─ Traceback (most recent call las─╮               

                             │ /app/.venv/lib/python3.12/site-p │               

                             │ ackages/axiestudio/services/data │               

                             │ base/service.py:355 in           │               

                             │ _run_migrations                  │               

                             │                                  │               

                             │   352 │   │   │                  │               

                             │   353 │   │   │   try:           │               

                             │   354 │   │   │   │   buffer.wri │               

                             │       migrations\n")             │               

                             │ ❱ 355 │   │   │   │   command.ch │               

                             │   356 │   │   │   except util.ex │               

                             │   357 │   │   │   │   logger.exc │               

                             │   358 │   │   │   │   if not fix │               

                             │                                  │               

                             │ /app/.venv/lib/python3.12/site-p │               

                             │ ackages/alembic/command.py:373   │               

                             │ in check                         │               

                             │                                  │               

                             │   370 │   │   diffs.extend(upgra │               

                             │   371 │                          │               

                             │   372 │   if diffs:              │               

                             │ ❱ 373 │   │   raise util.Autogen │               

                             │   374 │   │   │   f"New upgrade  │               

                             │   375 │   │   │   revision_conte │               

                             │   376 │   │   │   diffs=diffs,   │               

                             ╰──────────────────────────────────╯               

                             AutogenerateDiffsDetected: New      



   upgrade operations detected:                       

                             [('add_column', None, 'user',                      

                             Column('email', AutoString(),                      

                             table=<user>)), ('add_column', None,               

                             'user', Column('stripe_customer_id',               

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('subscription_status',                      

                             AutoString(), table=<user>,                        

                             default=ScalarElementColumnDefault('               

                             trial'))), ('add_column', None,                    

                             'user', Column('subscription_id',                  

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('trial_start', DateTime(),                  

                             table=<user>,                                      

                             default=CallableColumnDefault(<funct               

                             ion User.<lambda> at                               

                             0x7fb9780cca40>))), ('add_column',                 

                             None, 'user', Column('trial_end',                  

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('subscription_start',                       

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('subscription_end',                         

                             DateTime(), table=<user>)),                        

                             ('add_index', Index('ix_user_email',               


\ Launching Axie Studio...
| Launching Axie Studio...                    ERROR    2025-08-18 22:52:36 - ERROR    - utils  utils.py:59

                             - There's a mismatch between the models            

                             and the database.                                  

                             New upgrade operations detected:                   

                             [('add_column', None, 'user',                      

                             Column('email', AutoString(),                      

                             table=<user>)), ('add_column', None,               

                             'user', Column('stripe_customer_id',               

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('subscription_status',                      

                             AutoString(), table=<user>,                        

                             default=ScalarElementColumnDefault('tri            

                             al'))), ('add_column', None, 'user',               

                             Column('subscription_id', AutoString(),            

                             table=<user>)), ('add_column', None,               

                             'user', Column('trial_start',                      

                             DateTime(), table=<user>,                          

                             default=CallableColumnDefault(<function            

                             User.<lambda> at 0x7fb9780cca40>))),               

                             ('add_column', None, 'user',                       

                             DateTime(), table=<user>)),                        

                             Column('trial_end', DateTime(),                    

                             ('add_column', None, 'user',                       

                             table=<user>)), ('add_column', None,               

                             'user', Column('subscription_start',               

                             Column('subscription_end', DateTime(),             

                             table=<user>)), ('add_index',                      

                                 |       |     ->                               

                               File                                             

                             Index('ix_user_email', Column('email',             

                             <alembic.config.Config object at                   

                             AutoString(), table=<user>)))]Traceback            

                             "/app/.venv/lib/python3.12/site-package            

                             0x7fb8e9ede2d0>                                    

                                 |       -> <function check at                  

                             s/axiestudio/services/database/service.            

                             py", line 355, in _run_migrations                  

                             s/alembic/command.py'>                             

                                 command.check(alembic_cfg)                     

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             (most recent call last):                           

                             0x7fb992d8ede0>                                    

                             s/alembic/command.py", line 373, in                

                                 -> <module 'alembic.command' from   



                             Column('email', AutoString(),                      

                             table=<user>)), ('add_column', None,               

                             'user', Column('stripe_customer_id',               

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('subscription_status',                      

                             AutoString(), table=<user>,                        

                             default=ScalarElementColumnDefault('tri            

                             al'))), ('add_column', None, 'user',               

                             Column('subscription_id', AutoString(),            

                             table=<user>)), ('add_column', None,               

                             'user', Column('trial_start',                      

                             DateTime(), table=<user>,                          

                             default=CallableColumnDefault(<function            

                             User.<lambda> at 0x7fb9780cca40>))),               

                             ('add_column', None, 'user',                       

                             Column('trial_end', DateTime(),                    

                             table=<user>)), ('add_column', None,               

                             'user', Column('subscription_start',               

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('subscription_end', DateTime(),             

                             table=<user>)), ('add_index',                      

                             Index('ix_user_email', Column('email',             

                               File                                             

                             AutoString(), table=<user>)))]                     

                                                                                

                                                                                

                             "/app/.venv/lib/python3.12/site-package            

                             The above exception was the direct                 

                             s/click/core.py", line 1830, in invoke             

                             cause of the following exception:                  

                                                                                

                                 return                                         

                             _process_result(sub_ctx.command.invoke(            

                                                                                

                                                                                

                             sub_ctx))                                          

                             Traceback (most recent call last):                 

                                        |               |       |               

                                                                                

                               File "/app/.venv/bin/axiestudio",                

                             line 10, in <module>                               

                                 sys.exit(main())                               

                             |      -> <click.core.Context object at            

                                 |   |    -> <function main at                  

                             0x7fb8eb4256a0>                                    

                             0x7fba0088a840>                                    

                                        |               |       |               

                                 |   -> <built-in function exit>                

                                 -> <module 'sys' (built-in)>                   

                             -> <function Command.invoke at                     

                               File                                             

                             0x7fba006216c0>                                    

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/axiestudio_launcher.py",              

                                        |               |       ->              

                             line 20, in main                                   

                             <TyperCommand run>                                 

                                 axiestudio_main()                              

                                        |               ->                      

                                 -> <function main at                           

                             0x7fb8eb3aab60>                                    

                             <click.core.Context object at                      

                               File                                             

                             0x7fb8eb4256a0>                                    

                             "/app/.venv/lib/python3.12/site-package            

                                        -> <function                            

                             Group.invoke.<locals>._process_result              

                             s/axiestudio/__main__.py", line 834, in            

                             at 0x7fb8eb312340>                                 

                               File                                             

                             main                                               

                             "/app/.venv/lib/python3.12/site-package   

        app()                                          

                                 -> <typer.main.Typer object at                 

                             s/click/core.py", line 1226, in invoke             

                             0x7fb9ffce2d50>                                    

                                 return ctx.invoke(self.callback,               

                               File                                             

                             **ctx.params)                                      

                             "/app/.venv/lib/python3.12/site-package            

                                        |   |      |    |                       

                             s/typer/main.py", line 324, in __call__            

                             |   -> {'host': None, 'workers': None,             

                                 return get_command(self)(*args,                

                             'worker_timeout': None, 'port': None,              

                             **kwargs)                                          

                             'components_path':                                 

                                        |           |      |                    

                             PosixPath('/app/.venv/lib/python3.12...            

                             -> {}                                              

                                        |   |      |    |                       

                                        |           |      -> ()                

                                        |           ->                          

                             -> <click.core.Context object at                   

                             <typer.main.Typer object at                        

                             0x7fb8eb4256a0>                                    

                             0x7fb9ffce2d50>                                    

                                        -> <function get_command at             

                             0x7fb9ffcd6840>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/click/core.py", line 1442, in                    

                             __call__                                           

                                 return self.main(*args, **kwargs)              

                                        |    |     |       -> {}                

                                        |    |     -> ()                        

                                        |    -> <function                       

                             TyperGroup.main at 0x7fb9ffcd51c0>                 

                                        -> <TyperGroup >                        

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/typer/core.py", line 757, in main                

                                 return _main(                                  

                                        -> <function _main at                   

                             0x7fb9ffcd42c0>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/typer/core.py", line 195, in _main               

                                 rv = self.invoke(ctx)                          

                                      |    |      ->                            

                             <click.core.Context object at                      

                             0x7fb8eb6778c0>                                    

                                      |    -> <function Group.invoke            

                             at 0x7fba006228e0>                                 

                                        |   |      |    -> <function            

                             run at 0x7fb8eb312fc0>                             

                                        |   |      -> <TyperCommand             

                             run>                                               

                                        |   -> <function                        

                             Context.invoke at 0x7fba00620900>                  

                                        -> <click.core.Context                  

                             object at 0x7fb8eb4256a0>                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/click/core.py", line 794, in invoke              

                                 return callback(*args, **kwargs)               

                                        |         |       ->                    

                             {'host': None, 'workers': None,                    

                             'worker_timeout': None, 'port': None,              

                             'components_path':                                 

                             PosixPath('/app/.venv/lib/python3.12...            

                                        |         -> ()                         

                                        -> <function run at                     

                             0x7fb8eb312fc0>                   
         File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/typer/main.py", line 699, in wrapper             

                                 return callback(**use_params)                  

                                        |          -> {'host': None,            

                             'workers': None, 'worker_timeout':                 

                             None, 'port': None, 'components_path':             

                             PosixPath('/app/.venv/lib/python3.12...            

                                        -> <function run at                     

                             0x7fb8eb3aa020>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/__main__.py", line 375, in            

                             run                                                

                                 process_manager.webapp_process.star            

                             t()                                                

                                 |               |              ->              

                             <function BaseProcess.start at                     

                             0x7fb9fecdf600>                                    

                                 |               -> <Process                    

                             name='Process-1' parent=1 started>                 

                                 ->                                             

                             <axiestudio.__main__.ProcessManager                

                             object at 0x7fb8eb36f5f0>                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/multiprocess/process.py", line 121,              

                             in start                                           

                                 self._popen = self._Popen(self)                

                                 |    |        |    |      ->                   

                             <Process name='Process-1' parent=1                 

                             started>                                           

                                 |    |        |    ->                          

                             <staticmethod(<function Process._Popen             

                             at 0x7fb9fec7c180>)>                               

                                 |    |        -> <Process                      

                             name='Process-1' parent=1 started>                 

                                 |    -> None                                   

                                 -> <Process name='Process-1'                   

                             parent=1 started>                                  

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/multiprocess/context.py", line 224,              

                             in _Popen                                          

                                 return                                         

                             _default_context.get_context().Process.            

                             in __init__                                        

                                 self._launch(process_obj)                      

                                 |    |       -> <Process                       

                             _Popen(process_obj)                                

                             "/app/.venv/lib/python3.12/site-package            

                             name='Process-1' parent=1 started>                 

                             s/multiprocess/popen_fork.py", line 19,            

                                        |                |                      

    -> <Process name='Process-1' parent=1              

                             started>                                           

                                        |                ->                     

                             <function DefaultContext.get_context at            

                             0x7fb9fec7c360>                                    

                                        ->                                      

                             <multiprocess.context.DefaultContext               

                                 |    -> <function Popen._launch at             

                             in _launch                                         

                             object at 0x7fb9fecf3560>                          

                             0x7fb8e9e999e0>                                    

                               File                                             

                                 -> <multiprocess.popen_fork.Popen              

                             object at 0x7fb8e9e941d0>                          

                             "/app/.venv/lib/python3.12/site-package            

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             BaseProcess._bootstrap at                          

                             s/multiprocess/context.py", line 282,              

                             s/multiprocess/popen_fork.py", line 71,            

                             in _Popen                                          

                                 code =                                         

                                 return Popen(process_obj)                      

                             process_obj._bootstrap(parent_sentinel=            

                                        |     -> <Process                       

                             child_r)                                           

                                        |           |                           

                             name='Process-1' parent=1 started>                 

                                        -> <class                               

                             -> 8                                               

                                        |           -> <function                

                             'multiprocess.popen_fork.Popen'>                   

                               File                                             

                             0x7fb9fed00040>                                    

                                        -> <Process name='Process-1'            

                             parent=1 started>                                  

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/multiprocess/process.py", line 314,              

                             in _bootstrap                                      

                                 self.run()                                     

                                 |    -> <function BaseProcess.run              

                             at 0x7fb9fecdf560>                                 

                                 -> <Process name='Process-1'                   

                             parent=1 started>                                  

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/multiprocess/process.py", line 108,              

                             in run                                             

                                 self._target(*self._args,                      

                             **self._kwargs)                                    

                                 |    |        |    |        |    ->            

 

                                 |    |        |    |        ->                 

                             <Process name='Process-1' parent=1                 

                             started>                                           

                                 |    |        |    -> ()                       

                                 |    |        -> <Process                      

                             name='Process-1' parent=1 started>                 

                                 |    -> <bound method                          

                             BaseApplication.run of                             

                             <axiestudio.server.AxieStudioApplicatio            

                             n object at 0x7fb8e9f4a030>>                       

                                 -> <Process name='Process-1'                   

                             parent=1 started>                                  

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/gunicorn/app/base.py", line 71, in               

                             run                                                

                                 Arbiter(self).run()                            

                                 |       ->                             

                             s/gunicorn/arbiter.py", line 201, in               

                             run                                                

                                 self.manage_workers()                          

                                 |    -> <function                              

                             s/uvicorn/workers.py", line 75, in                 

                             Arbiter.manage_workers at                          

                             0x7fb8e9e21620>                                    

                             init_process                                       

                                 -> <gunicorn.arbiter.Arbiter object            

                             at 0x7fb9fecf2fc0>                                 

                                 super().init_process()                         

                               File                                             

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             "/app/.venv/lib/python3.12/site-package            

                             s/gunicorn/arbiter.py", line 570, in               

                             s/gunicorn/workers/base.py", line 143,             

                             manage_workers                                     

                                 self.spawn_workers()                           

                             in init_process                                    

                                 |    -> <function                              

                                 self.run()                                     

                             Arbiter.spawn_workers at                           

                                 |    -> <function UvicornWorker.run            

                             0x7fb8e9e21760>                                    

                                 -> <gunicorn.arbiter.Arbiter object            

                             at 0x7fb9fecf2fc0>                                 

                             at 0x7fb8e9e7f7e0>                                 

                               File                                             

                                 ->                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/gunicorn/arbiter.py", line 641, in               

                             <axiestudio.server.AxieStudioUvicornWor            

                             spawn_workers                                      

                                 self.spawn_worker()                            

                             ker object at 0x7fb8eb3cf380>                      

                                 |    -> <function                              

                             Arbiter.spawn_worker at 0x7fb8e9e216c0>            

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                                 -> <gunicorn.arbiter.Arbiter object            

                             s/uvicorn/workers.py", line 107, in run            

                             at 0x7fb9fecf2fc0>                                 

                                 return asyncio.run(self._serve())              

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/gunicorn/arbiter.py", line 608, in               

                             spawn_worker                                       

                                 worker.init_process()                          

                                 |      -> <function                            

                             UvicornWorker.init_process at                      

                             0x7fb8e9e225c0>                                    

                                 ->                                             

                             <axiestudio.server.AxieStudioUvicornWor            

                             ker object at 0x7fb8eb3cf380>                      

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                                        |       |   |    ->                     

                             <function                                          

                             AxieStudioUvicornWorker._serve at                  

                             0x7fb8e9e7fa60>                                    

                                        |       |   ->                          

                             <axiestudio.server.AxieStudioUvicornWor            

                             ker object at 0x7fb8eb3cf380>                      

                                        |       -> <function run at             

                             0x7fb9ffb5c180>                                    

                                        -> <module 'asyncio' from               

                             '/usr/local/lib/python3.12/asyncio/__in            

                             it__.py'>                                          

                               File                                             

                             "/usr/local/lib/python3.12/asyncio/runn            

                             ers.py", line 194, in run

    return runner.run(main)                        

                                        |      |   -> <coroutine                

                             object AxieStudioUvicornWorker._serve              

                             at 0x7fb8e9e80ad0>                                 

                                        |      -> <function                     

                             Runner.run at 0x7fb9ffa25da0>                      

                                        -> <asyncio.runners.Runner              

                             object at 0x7fb8ea042ba0>                          

                               File                                             

                             "/usr/local/lib/python3.12/asyncio/runn            

                             ers.py", line 118, in run                          

                                 return                                         

                             self._loop.run_until_complete(task)                

                                        |    |     |                            

                             -> <Task pending name='Task-1'                     

                             coro=<AxieStudioUvicornWorker._serve()             

                             running at                                         

                             /app/.venv/lib/python3.12/site-packages            

                             /axiestu...                                        

                                        |    |     -> <function                 

                             BaseEventLoop.run_until_complete at                

                             0x7fb9ffa879c0>                                    

                                        |    ->                                 

                             <_UnixSelectorEventLoop running=True               

                             closed=False debug=False>                          

                                        -> <asyncio.runners.Runner              

                             object at 0x7fb8ea042ba0>                          

                                                        |      ->               

                             method LifespanOn.receive of                       

                             │   372 │   if diffs:                 │            


/ Launching Axie Studio...
- Launching Axie Studio...                    ERROR    2025-08-18 22:52:36 - ERROR    - main - main.py:236

                             There's a mismatch between the models              

                             and the database.                                  

                             New upgrade operations detected:                   

                             [('add_column', None, 'user',                      

                             Column('email', AutoString(),                      

                             table=<user>)), ('add_column', None,               

                             'user', Column('stripe_customer_id',               

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('subscription_status',                      

                             AutoString(), table=<user>,                        

                             default=ScalarElementColumnDefault('tri            

                             al'))), ('add_column', None, 'user',               

                             Column('subscription_id', AutoString(),            

                             table=<user>)), ('add_column', None,               

                             'user', Column('trial_start',                      

                             DateTime(), table=<user>,                          

                             default=CallableColumnDefault(<function            

                             User.<lambda> at 0x7fb9780cca40>))),               

                             ('add_column', None, 'user',                       

                             Column('trial_end', DateTime(),                    

                             table=<user>)), ('add_column', None,               

                             'user', Column('subscription_start',               

                             table=<user>)), ('add_index',                      

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Index('ix_user_email', Column('email',             

                             Column('subscription_end', DateTime(),             

                             AutoString(), table=<user>)))]Traceback            

                             (most recent call last):                           

                                                                                

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/services/database/service.            

                             0x7fb992d8ede0>                                    

                             py", line 355, in _run_migrations                  

                                 -> <module 'alembic.command' from              

                                 command.check(alembic_cfg)                     

                             '/app/.venv/lib/python3.12/site-package    

         |       |     ->                               

                             s/alembic/command.py'>                             

                             <alembic.config.Config object at                   

                               File                                             

                             0x7fb8e9ede2d0>                                    

                             "/app/.venv/lib/python3.12/site-package            

                                 |       -> <function check at                  

                             Column('subscription_id', AutoString(),            

                             '/app/.venv/lib/python3.12/site-package            

                             alembic.util.exc.AutogenerateDiffsDetec            

                             default=ScalarElementColumnDefault('tri            

                             s/alembic/util/__init__.py'>                       

                             table=<user>)), ('add_column', None,               

                             al'))), ('add_column', None, 'user',               

                             ted: New upgrade operations detected:              

                             AutoString(), table=<user>)),                      

                             'user', Column('trial_start',                      

                                                                                

                             Column('subscription_status',                      

                             ('add_column', None, 'user',                       

                             [('add_column', None, 'user',                      

                             AutoString(), table=<user>,                        

                                       |    -> <class                           

                             Column('email', AutoString(),                      

                             'alembic.util.exc.AutogenerateDiffsDete            

                             table=<user>)), ('add_column', None,               

                             cted'>                                             

                             s/alembic/command.py", line 373, in                

                             'user', Column('stripe_customer_id',               

                                       -> <module 'alembic.util'                

                             check                                              

                             from                                               

                                 raise                                          

                             util.AutogenerateDiffsDetected(                    

                             DateTime(), table=<user>,                          

                             default=CallableColumnDefault(<function            

                             User.<lambda> at 0x7fb9780cca40>))),               

                             ('add_column', None, 'user',                       

                             Column('trial_end', DateTime(),                    

                             table=<user>)), ('add_column', None,               

                             'user', Column('subscription_start',               

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('subscription_end', DateTime(),             

                             table=<user>)), ('add_index',                      

                             Index('ix_user_email', Column('email',             

                             AutoString(), table=<user>)))]                     

                                                                                

                                                                                

                             The above exception was the direct                 

                             cause of the following exception:                  

                                                               


                             Traceback (most recent call last):                 

                                                                                

                               File "/app/.venv/bin/axiestudio",                

                             line 10, in <module>                               

                                 sys.exit(main())                               

                                 |   |    -> <function main at                  

                             0x7fba0088a840>                                    

                                 |   -> <built-in function exit>                

                                 -> <module 'sys' (built-in)>                   

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/axiestudio_launcher.py",              

                             line 20, in main                                   

                                 axiestudio_main()                              

                                 -> <function main at                           

                             0x7fb8eb3aab60>                                    

                                 -> <typer.main.Typer object at                 

                             0x7fb9ffce2d50>                                    

                               File                                             

                             __call__                                           

                                        -> <function get_command at             

                             "/app/.venv/lib/python3.12/site-package            

                                 return self.main(*args, **kwargs)              

                             0x7fb9ffcd6840>                                    

                             s/typer/main.py", line 324, in __call__            

                                 return get_command(self)(*args,                

                             **kwargs)                                          

                                        |           |      |                    

                               File                                             

                             -> {}                                              

                             "/app/.venv/lib/python3.12/site-package            

                                        |           ->                          

                             s/click/core.py", line 1442, in                    

                             <typer.main.Typer object at                        

                               File                                             

                                        |           |      -> ()                

                             0x7fb9ffce2d50>                                    

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/__main__.py", line 834, in            

                             main                                               

                                 app()                                          

                                 -> <gunicorn.arbiter.Arbiter object            

                             _events.py", line 1987, in _run_once               

                             leware object at 0x7fb8e9eb7110>                   

                                       |    |   |      |        ->              

                               File                                             

                             BaseEventLoop.run_in_executor at                   

                             │   363 │   │   │   │   self.try_down │            


\ Launching Axie Studio...
+ Stopping Server (0.10s)


\ Cancelling Background Tasks...
| Launching Axie Studio...
+ Cancelling Background Tasks


| Cleaning Up Services...                    DEBUG    2025-08-18 22:52:37 - DEBUG    - utils utils.py:104

                             - AUTO_LOGIN is set to False. Removing             

                             default superuser if exists.                       


/ Launching Axie Studio...
/ Cleaning Up Services...
- Launching Axie Studio...
- Cleaning Up Services...
\ Launching Axie Studio...
\ Cleaning Up Services...
| Launching Axie Studio...
| Cleaning Up Services...
/ Launching Axie Studio...
/ Cleaning Up Services...


- Launching Axie Studio...
- Cleaning Up Services...
\ Launching Axie Studio...
| Launching Axie Studio...
\ Cleaning Up Services...
/ Launching Axie Studio...
| Cleaning Up Services...
- Launching Axie Studio...
/ Cleaning Up Services...
\ Launching Axie Studio...


- Cleaning Up Services...
| Launching Axie Studio...
\ Cleaning Up Services...
/ Launching Axie Studio...                    ERROR    2025-08-18 22:52:37 - ERROR    - utils utils.py:119

                             - (psycopg.errors.UndefinedColumn)                 

                             column user.email does not exist                   

                             LINE 1: SELECT "user".id,                          

                             "user".username, "user".email,                     

                             "user".pass...                                     

                                                              
                             "user".device_fingerprint,                         

                             "user".stripe_customer_id,                         

                             "user".subscription_status,                        

                             "user".subscription_id,                            

                             "user".trial_start, "user".trial_end,              

                             "user".subscription_start,                         

                             "user".subscription_end,                           

                             "user".store_api_key, "user".optins                

                             FROM "user"                                        

                             WHERE "user".username =                            

                             %(username_1)s::VARCHAR]                           

                                                                                

                             (Background on this error at:                      

                             https://sqlalche.me/e/20/f405)Tracebac             

                             k (most recent call last):                         

                                                                                

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/services/database/servic             

                             Column('subscription_status',                      

                             AutoString(), table=<user>,                        

                             e.py", line 355, in _run_migrations                

                             '/app/.venv/lib/python3.12/site-packag             

                                 raise                                          

                                 command.check(alembic_cfg)                     

                             util.AutogenerateDiffsDetected(                    

                             es/alembic/command.py'>                            

                             <alembic.config.Config object at                   

                                 |       |     ->                               

                                       |    -> <class                           

                               File                                             

                             0x7fb8e9ede2d0>                                    

                             "/app/.venv/lib/python3.12/site-packag             

                             'alembic.util.exc.AutogenerateDiffsDet             

                                 |       -> <function check at                  

                             cted: New upgrade operations detected:             

                                       -> <module 'alembic.util'                

                             ected'>                                            

                             0x7fb992d8ede0>                                    

                             from                                               

                             [('add_column', None, 'user',                      

                             es/alembic/command.py", line 373, in               

                             'user', Column('stripe_customer_id',               

                                 -> <module 'alembic.command' from              

                             '/app/.venv/lib/python3.12/site-packag             

                             check                                              

                             es/alembic/util/__init__.py'>                      

                             AutoString(), table=<user>)),                      

                             table=<user>)), ('add_column', None,               

                             ('add_column', None, 'user',                       

                                                                                

                             alembic.util.exc.AutogenerateDiffsDete             

                             default=ScalarElementColumnDefault('tr             

                             ial'))), ('add_column', None, 'user',              

                             Column('subscription_id',                          

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('trial_start', DateTime(),                  

                             table=<user>,                                      

                             default=CallableColumnDefault(<functio             

                             n User.<lambda> at 0x7fb9780cca40>))),             

                             ('add_column', None, 'user',                       

                             Column('trial_end', DateTime(),                    

                             table=<user>)), ('add_column', None,               

                             'user', Column('subscription_start',               

                             DateTime(), table=<user>)),                        

                             ('add_column', None, 'user',                       

                             Column('subscription_end', DateTime(),             

                             table=<user>)), ('add_index',                      

                             Index('ix_user_email', Column('email',             

                             AutoString(), table=<user>)))]                     

                                                                     

         The above exception was the direct                 

                             cause of the following exception:                  

                                                                                

                                                                                

                             Traceback (most recent call last):                 

                                                                                

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/main.py", line 146, in               

                             lifespan                                           

                                 await                                          

                             initialize_services(fix_migration=fix_             

                             migration)                                         

                                       |                                        

                             -> False                                           

                                       -> <function                             

                             initialize_services at 0x7fb96c97cf40>             

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/services/utils.py", line             

                             227, in initialize_services                        

                                 await                                          

                             initialize_database(fix_migration=fix_             

                             migration)                                         

                                       |                                        

                             -> False                                           

                                       -> <function                             

                             initialize_database at 0x7fb96d77e020>             

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/services/database/utils.             

                             py", line 40, in initialize_database               

                                 await                                          

                             database_service.run_migrations(fix=fi             

                             x_migration)                                       

                                       |                |                       

                             -> False                                           

                                       |                ->                      

                             <function                                          

                             DatabaseService.run_migrations at                  

                             0x7fb96c97db20>                                    

                                       ->                                       

                             <axiestudio.services.database.service.             

                             DatabaseService object at                          

                             0x7fb8eb36f8f0>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/services/database/servic             

                             e.py", line 375, in run_migrations                 

                                 await                                          

                             asyncio.to_thread(self._run_migrations             

                             , should_initialize_alembic, fix)                  

                                       |       |         |    |                 

                             |                          -> False                

                                       |       |         |    |                 

                             -> False                                           

                                       |       |         |    ->                

                             <function                                          

                             DatabaseService._run_migrations at                 

                             0x7fb96c97da80>                                    

                                       |       |         ->                     

                             <axiestudio.services.database.service.             

                             DatabaseService object at                          

                             0x7fb8eb36f8f0>                                    

                                       |       -> <function                     

                             to_thread at 0x7fb9ffa4a8e0>                       

                                       -> <module 'asyncio' from                

                             '/usr/local/lib/python3.12/asyncio/__i             

                             nit__.py'>                          
      "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/services/database/servic             

                             e.py", line 375, in run_migrations                 

                                 await                                          

                             asyncio.to_thread(self._run_migrations             

                             , should_initialize_alembic, fix)                  

                                       |       |         |    |                 

                             |                          -> False                

                                       |       |         |    |                 

                             -> False                                           

                                       |       |         |    ->                

                             <function                                          

                             DatabaseService._run_migrations at                 

                             0x7fb96c97da80>                                    

                                       |       |         ->                     

                             <axiestudio.services.database.service.             

                             DatabaseService object at                          

                             0x7fb8eb36f8f0>                                    

                                       |       -> <function                     

                             to_thread at 0x7fb9ffa4a8e0>                       

                                       -> <module 'asyncio' from                

                             '/usr/local/lib/python3.12/asyncio/__i             

                             nit__.py'>                                         

                               File                                             

                             "/usr/local/lib/python3.12/asyncio/thr             

                             eads.py", line 25, in to_thread                    

                                 return await                                   

                             loop.run_in_executor(None, func_call)              

                                              |    |                            

                             Column('trial_end', DateTime(),                    

                             -> functools.partial(<built-in method              

                             run of _contextvars.Context object at              

                             table=<user>)), ('add_column', None,               

                             0x7fb9f8db4200>, <bound method                     

                             'user', Column('subscription_start',               

                             DatabaseService._run_...                           

                             DateTime(), table=<user>)),                        

                                              |    -> <function                 

                             ('add_column', None, 'user',                       

                             BaseEventLoop.run_in_executor at                   

                             Column('subscription_end', DateTime(),             

                             0x7fb9ffa242c0>                                    

                             table=<user>)), ('add_index',                      

                                              ->                                

                             Index('ix_user_email', Column('email',             

                             <_UnixSelectorEventLoop running=True               

                             AutoString(), table=<user>)))]                     

                             closed=False debug=False>                          

                                                                                

                               File               

        "/usr/local/lib/python3.12/concurrent/             

                             During handling of the above                       

                             futures/thread.py", line 58, in run                

                             exception, another exception occurred:             

                                 result = self.fn(*self.args,                   

                                                                                

                             **self.kwargs)                                     

                                                                                

                             Traceback (most recent call last):                 

                                          |        |            ->              

                                                                                

                             None                                               

                                          |        -> None                      

                                          -> None                               

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/services/database/servic             

                             e.py", line 360, in _run_migrations                

                                 raise RuntimeError(msg) from exc               

                                                    |         ->                

                             <module 'sqlalchemy.exc' from                      

                                 ->                                             

                             '/app/.venv/lib/python3.12/site-packag             

                             <sqlalchemy.dialects.postgresql.psycop             

                             es/sqlalchemy/exc.py'>                             

                               File                                             

                                                    -> "There's a               

                             "/app/.venv/lib/python3.12/site-packag             

                             es/sqlalchemy/engine/base.py", line                

                             mismatch between the models and the                

                             1963, in _exec_single_context                      

                             database.\nNew upgrade operations                  

                                 self.dialect.do_execute(                       

                             detected: [('add_column', None,                    

                                 |    |       -> <function                      

                             'user', Colu...                                    

                             DefaultDialect.do_execute at                       

                                                                                

                             0x7fb9fe314c20>                                    

                                 |    ->                                        

                             RuntimeError: There's a mismatch                   

                             <sqlalchemy.dialects.postgresql.psycop             

                             g.PGDialectAsync_psycopg object at                 

                             between the models and the database.               

                             0x7fb8e9f90b90>                                    

                                 ->                                             

                             New upgrade operations detected:                   

                             <sqlalchemy.engine.base.Connection                 

                             [('add_column', None, 'user',                      

                             object at 0x7fb9f8b4ade0>                          

                             Column('email', AutoString(),                      

                               File                                  

     table=<user>)), ('add_column', None,               

                             "/app/.venv/lib/python3.12/site-packag             

                             'user', Column('stripe_customer_id',               

                             es/sqlalchemy/engine/default.py", line             

                             AutoString(), table=<user>)),                      

                             943, in do_execute                                 

                             ('add_column', None, 'user',                       

                                 cursor.execute(statement,                      

                             Column('subscription_status',                      

                             parameters)                                        

                             AutoString(), table=<user>,                        

                                 |      |       |          ->                   

                             default=ScalarElementColumnDefault('tr             

                             {'username_1': 'axiestudio'}                       

                             ial'))), ('add_column', None, 'user',              

                                 |      |       -> 'SELECT                      

                             "user".id, "user".username,                        

                             Column('subscription_id',                          

                             "user".email, "user".password,                     

                             AutoString(), table=<user>)),                      

                             "user".profile_image,                              

                             ('add_column', None, 'user',                       

                             "user".is_active,                                  

                             "user".is_superuse...                              

                             Column('trial_start', DateTime(),                  

                                 |      -> <function                            

                             table=<user>,                                      

                             AsyncAdapt_psycopg_cursor.execute at               

                             0x7fb995fc1940>                                    

                             default=CallableColumnDefault(<functio             

                             n User.<lambda> at 0x7fb9780cca40>))),             

                             ('add_column', None, 'user',                       

                             g.AsyncAdapt_psycopg_cursor object at              

                             0x7fb9f866fe40>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/sqlalchemy/dialects/postgresql/psyc             

                             opg.py", line 594, in execute                      

                                 result =                                       

                             self.await_(self._cursor.execute(query             

                             , params, **kw))                                   

                                          |    |      |    |                    

                             |      |         -> {}                             

                                          |    |      |    |                    

                             |      -> {'username_1': 'axiestudio'}             

                                          |    |      |    |                    

                             -> 'SELECT "user".id, "user".username,             

                             "user".email, "user".password,                     

                             "user".profile_image,                              

                             "user".is_active,                                  

                             "user".is_superuse...                              

                                          |    |      |    ->                   

                             <member '_cursor' of                               

                             'AsyncAdapt_psycopg_cursor' objects>               

                                          |    |      ->                        

                             <sqlalchemy.dialects.postgresql.psycop             

                             g.AsyncAdapt_psycopg_cursor object at              

                             0x7fb9f866fe40>                                    

                                          |    -> <member 'await_'              

                             of 'AsyncAdapt_psycopg_cursor'                     

                             objects>                              

   <sqlalchemy.dialects.postgresql.psycop             

                             g.AsyncAdapt_psycopg_cursor object at              

                             0x7fb9f866fe40>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/sqlalchemy/util/_concurrency_py3k.p             

                             y", line 132, in await_only                        

                                 return                                         

                             current.parent.switch(awaitable)  #                

                             type: ignore # noqa: E501                          

                                        |       |             ->                

                             <coroutine object AsyncCursor.execute              

                             at 0x7fb9f8a0fac0>                                 

                                        |       -> <attribute                   

                             'parent' of 'greenlet.greenlet'                    

                             objects>                                           

                                        -> <_AsyncIoGreenlet object             

                             at 0x7fb9f87f66c0                                  

                             (otid=0x7fb9fec655f0) dead>                        

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/sqlalchemy/util/_concurrency_py3k.p             

                             y", line 196, in greenlet_spawn                    

                                 value = await result                           

                                               -> <coroutine object             

                             AsyncCursor.execute at 0x7fb9f8a0fac0>             

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/psycopg/cursor_async.py", line 97,              

                             in execute                                         

                                 raise ex.with_traceback(None)                  

                                                                                

                             psycopg.errors.UndefinedColumn: column             

                             user.email does not exist                          

                             LINE 1: SELECT "user".id,                          

                             "user".username, "user".email,                     

                             "user".pass...                                     

                                                                                

                                  ^                                             

                                                                                

                                                                                

                             The above exception was the direct                 

                             cause of the following exception:                  

                                                                                

                                                                    

 Traceback (most recent call last):                 

                                                                                

                               File "/app/.venv/bin/axiestudio",                

                             line 10, in <module>                               

                                 sys.exit(main())                               

                                 |   |    -> <function main at                  

                             0x7fba0088a840>                                    

                                 |   -> <built-in function exit>                

                                 -> <module 'sys' (built-in)>                   

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/axiestudio_launcher.py",             

                              line 20, in main                                  

                                 axiestudio_main()                              

                                 -> <function main at                           

                             0x7fb8eb3aab60>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/__main__.py", line 834,              

                             in main                                            

                                 app()                                          

                                 -> <typer.main.Typer object at                 

                             0x7fb9ffce2d50>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/typer/main.py", line 324, in                    

                             __call__                                           

                                 return get_command(self)(*args,                

                             **kwargs)                                          

                                        |           |      |                    

                             -> {}                                              

                                        |           |      -> ()                

                                        |           ->                          

                             <typer.main.Typer object at                        

                             0x7fb9ffce2d50>                                    

                                        -> <function get_command at             

                             0x7fb9ffcd6840>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/click/core.py", line 1442, in                   

                             __call__                                           

                                 return self.main(*args, **kwargs)              

                                        |    |     |       -> {}                

                                        |    |     -> ()                        

                                        |    -> <function                       

                             TyperGroup.main at 0x7fb9ffcd51c0>                 

                                        -> <TyperGroup >                        

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/typer/core.py", line 757, in main               

                                 return _main(                                  

                                        -> <function _main at                   

                             0x7fb9ffcd42c0>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/typer/core.py", line 195, in _main              

                                 rv = self.invoke(ctx)                          


   <click.core.Context object at                      

                             0x7fb8eb6778c0>                                    

                                      |    -> <function                         

                             Group.invoke at 0x7fba006228e0>                    

                                      -> <TyperGroup >                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/click/core.py", line 1830, in                   

                             invoke                                             

                                 return                                         

                             _process_result(sub_ctx.command.invoke             

                             (sub_ctx))                                         

                                        |               |       |               

                             |      -> <click.core.Context object               

                             at 0x7fb8eb4256a0>                                 

                                        |               |       |               

                             -> <function Command.invoke at                     

                             0x7fba006216c0>                                    

                                        |               |       ->              

                             <TyperCommand run>                                 

                                        |               ->                      

                             <click.core.Context object at                      

                             0x7fb8eb4256a0>                                    

                                        -> <function                            

                             Group.invoke.<locals>._process_result              

                             at 0x7fb8eb312340>                                 

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/click/core.py", line 1226, in                   

                             invoke                                             

                                 return ctx.invoke(self.callback,               

                             **ctx.params)                                      

                                        |   |      |    |                       

                             |   -> {'host': None, 'workers': None,             

                             'worker_timeout': None, 'port': None,              

                             'components_path':                                 

                             PosixPath('/app/.venv/lib/python3.12..             

                             .                                                  

                                        |   |      |    |                       

                             -> <click.core.Context object at                   

                             0x7fb8eb4256a0>                                    

                                        |   |      |    ->                      

                             <function run at 0x7fb8eb312fc0>                   

                                        |   |      -> <TyperCommand             

                             run>                                               

                                        |   -> <function                        

                             Context.invoke at 0x7fba00620900>                  

                                        -> <click.core.Context                  

                             object at 0x7fb8eb4256a0>                          

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/click/core.py", line 794, in invoke             

                                 return callback(*args, **kwargs)               

                                        |         |       ->                    

                             {'host': None, 'workers': None,                    

                             'worker_timeout': None, 'port': None,              

                             'components_path':                                 

                             PosixPath('/app/.venv/lib/python3.12..   

               |         -> ()                         

                                        -> <function run at                     

                             0x7fb8eb312fc0>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/typer/main.py", line 699, in                    

                             wrapper                                            

                                 return callback(**use_params)                  

                                        |          -> {'host':                  

                             None, 'workers': None,                             

                             'worker_timeout': None, 'port': None,              

                             'components_path':                                 

                             PosixPath('/app/.venv/lib/python3.12..             

                             .                                                  

                                        -> <function run at                     

                             0x7fb8eb3aa020>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-packag             

                             es/axiestudio/__main__.py", line 375,              

                             in run                                             


- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...


| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...[08/18/25 22:52:39] ERROR    2025-08-18 22:52:39 - ERROR    - main - main.py:289

                             Unhandled error during cleanup: Could              

                             not remove default superuser.Traceback             

                             (most recent call last):                           

                                                                                

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/services/database/service.            

                             py", line 355, in _run_migrations                  

                                 command.check(alembic_cfg)                     

                                 |       |     ->                               

                             <alembic.config.Config object at                   

                             0x7fb8e9ede2d0>                                    

                                 |       -> <function check at                  

                             0x7fb992d8ede0>                                    

                                 -> <module 'alembic.command' from              

                             '/app/.venv/lib/python3.12/site-package            

                             s/alembic/command.py'>                             

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/alembic/command.py", line 373, in                

                             check                                              

                                 raise                                          

                             util.AutogenerateDiffsDetected(                    

                                       |    -> <class                           

                             'alembic.util.exc.AutogenerateDiffsDete            

                             cted'>                                             

                                       -> <module 'alembic.util'                

                             from                                               

                             '/app/.venv/lib/python3.12/site-package            

                             s/alembic/util/__init__.py'>                  

     alembic.util.exc.AutogenerateDiffsDetec            

                             ted: New upgrade operations detected:              

                             [('add_column', None, 'user',                      

                             Column('email', AutoString(),                      

                             table=<user>)), ('add_column', None,               

                             'user', Column('stripe_customer_id',               

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('subscription_status',                      

                             AutoString(), table=<user>,                        

                             default=ScalarElementColumnDefault('tri            

                             al'))), ('add_column', None, 'user',               

                             Column('subscription_id', AutoString(),            

                             table=<user>)), ('add_column', None,               

                             'user', Column('trial_start',                      

                             DateTime(), table=<user>,                          

                             default=CallableColumnDefault(<function            

                             User.<lambda> at 0x7fb9780cca40>))),               

                             ('add_column', None, 'user',                       

                             Column('trial_end', DateTime(),                    

                                 await                                          

                             table=<user>)), ('add_column', None,               

                             'user', Column('subscription_start',               

                             DateTime(), table=<user>)),                        

                             asyncio.to_thread(self._run_migrations,            

                             ('add_column', None, 'user',                       

                             should_initialize_alembic, fix)                    

                             Column('subscription_end', DateTime(),             

                                       |       |         |    |                 

                             table=<user>)), ('add_index',                      

                                       |       |         |    ->                

                             Index('ix_user_email', Column('email',             

                             <function                                          

                             <axiestudio.services.database.service.D            

                             DatabaseService._run_migrations at                 

                                       |       |         ->                     

                             |                          -> False                

                             0x7fb96c97da80>                                    

                             atabaseService object at                           

                                       |       |         |    |                 

                             -> False                                           

                             '/usr/local/lib/python3.12/asyncio/__in            

                             it__.py'>                                          

                               File                                             

                             "/usr/local/lib/python3.12/asyncio/thre            

                             ads.py", line 25, in to_thread                     

                                 return await                                   

                             0x7fb8eb36f8f0>                                    

                                       |       -> <function                     

                             to_thread at 0x7fb9ffa4a8e0>                       

                                       -> <module 'asyncio' from                

                             loop.run_in_executor(None, func_call)              

                                              |    |                            

                             utures/thread.py", line 58, in run                 

                             -> functools.partial(<built-in method              

                                 result = self.fn(*self.args,                   

                             **self.kwargs)                                     

                             run of _contextvars.Context object at              

                             0x7fb9f8db4200>, <bound method                     

                             DatabaseService._run_...                           

                                              |    -> <function                 

                             BaseEventLoop.run_in_executor at                   

                             0x7fb9ffa242c0>                                    

                                              ->                                

                             <_UnixSelectorEventLoop running=True               

                             closed=False debug=False>                          

                               File                                             

                             "/usr/local/lib/python3.12/concurrent/f            

                                          |        |            ->              

                             None                                               

                   -> None                               

                                          |        -> None                      

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                                 raise RuntimeError(msg) from exc               

                             s/axiestudio/services/database/service.            

                                                    |         ->                

                             py", line 360, in _run_migrations                  

                             <module 'sqlalchemy.exc' from                      

                             '/app/.venv/lib/python3.12/site-package            

                             s/sqlalchemy/exc.py'>                              

                                                    -> "There's a               

                             mismatch between the models and the                

                             database.\nNew upgrade operations                  

                             Colu...                                            

                                                                                

                             RuntimeError: There's a mismatch                   

                             between the models and the database.               

                             detected: [('add_column', None, 'user',            

                             New upgrade operations detected:                   

                             Column('email', AutoString(),                      

                             [('add_column', None, 'user',                      

                             table=<user>)), ('add_column', None,               

                             'user', Column('stripe_customer_id',               

                             AutoString(), table=<user>)),                      

                             ('add_column', None, 'user',                       

                             Column('subscription_status',                      

                             AutoString(), table=<user>,                        

                             default=ScalarElementColumnDefault('tri            

                             al'))), ('add_column', None, 'user',               

                             Column('subscription_id', AutoString(),            

                             table=<user>)), ('add_column', None,               

                             'user', Column('trial_start',                      

                             ('add_column', None, 'user',                       

                             DateTime(), table=<user>,                          

                             Column('subscription_end', DateTime(),             

                             default=CallableColumnDefault(<function            

                             User.<lambda> at 0x7fb9780cca40>))),               

                             table=<user>)), ('add_column', None,               

                             ('add_column', None, 'user',                       

                             'user', Column('subscription_start',               

                             Column('trial_end', DateTime(),                    

                             DateTime(), table=<user>)),                        

                             table=<user>)), ('add_index',                      

                             Index('ix_user_email', Column('email',             

                             AutoString(), table=<user>)))]                     

                                                                                

                                                                                

                             AutoString(), table=<user>)))]                     

                                                                                

                                                                                

                             The above exception was the direct                 

                             cause of the following exception:                  

                                                                                

                                                                                

                             Traceback (most recent call last):                 

                                                                                

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/main.py", line 146, in                

                             lifespan                                           

                                 await                                          

                             initialize_services(fix_migration=fix_m            

                             igration)                                          

                                       |                                        

                             -> False                                           

                                       -> <function               
  initialize_services at 0x7fb96c97cf40>             

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/services/utils.py", line              

                             227, in initialize_services                        

                                 await                                          

                             initialize_database(fix_migration=fix_m            

                             igration)                                          

                                       |                                        

                             -> False                                           

                                       -> <function                             

                             initialize_database at 0x7fb96d77e020>             

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/services/database/utils.py            

                             ", line 40, in initialize_database                 

                                 await                                          

                             database_service.run_migrations(fix=fix            

                             _migration)                                        

                                       |                |                       

                             -> False                                           

                                       |                -> <function            

                             DatabaseService.run_migrations at                  

                             0x7fb96c97db20>                                    

                                       ->                                       

                             <axiestudio.services.database.service.D            

                             atabaseService object at                           

                             0x7fb8eb36f8f0>                                    

                               File                                             

                             "/app/.venv/lib/python3.12/site-package            

                             s/axiestudio/services/database/service.            

                             py", line 375, in run_migrations                   


| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...


- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...


| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...


- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...

Railway rate limit of 500 logs/sec reached for replica, update your application to reduce the logging rate. Messages dropped: 1849


| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...


- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...
| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ Launching Axie Studio...


| Launching Axie Studio...
/ Launching Axie Studio...
- Launching Axie Studio...
\ 

   

