REcehck the error logs again! 



Exception in ASGI application

  + Exception Group Traceback (most recent call last):

  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 76, in collapse_excgroups

  |     yield

  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 177, in __call__

  |     async with anyio.create_task_group() as task_group:

  |                ^^^^^^^^^^^^^^^^^^^^^^^^^

  |   File "/app/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 772, in __aexit__

  |     raise BaseExceptionGroup(

  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)

  +-+---------------- 1 ----------------

    | Traceback (most recent call last):

    |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi

    |     result = await app(  # type: ignore[func-returns-value]

    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    |     return await self.app(scope, receive, send)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__

    |     await super().__call__(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__

    |     await self.middleware_stack(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    |     await self.app(scope, receive, _send)

    |   File "/app/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 745, in __call__

    |     await self.app(scope, otel_receive, otel_send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    |     await self.app(scope, receive, _send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 376, in flatten_query_string_lists

    |     return await call_next(request)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     response = await self.dispatch_func(request, call_next)

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 366, in check_boundary

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     return await call_next(request)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 99, in dispatch

    |     raise app_exc

    |     response = await call_next(request)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |                ^^^^^^^^^^^^^^^^^^^^^^^^

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     await self.simple_response(scope, receive, send, request_headers=headers)

    |     raise app_exc

    |     with recv_stream, send_stream, collapse_excgroups():

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    |                                    ^^^^^^^^^^^^^^^^^^^^



 File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 376, in flatten_query_string_lists

    |     return await call_next(request)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     response = await self.dispatch_func(request, call_next)

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 366, in check_boundary

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     return await call_next(request)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 99, in dispatch

    |     raise app_exc

    |     response = await call_next(request)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |                ^^^^^^^^^^^^^^^^^^^^^^^^

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     await self.simple_response(scope, receive, send, request_headers=headers)

    |     raise app_exc

    |     with recv_stream, send_stream, collapse_excgroups():

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |     self.gen.throw(value)

    |     await self.app(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/middleware.py", line 59, in __call__

    |     raise exc

    |     await self.app(scope, receive, send)

    |     await self.app(scope, wrapper, send)


File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)

    |     response = await self.dispatch_func(request, call_next)

    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    |     raise exc

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    |     await app(scope, receive, sender)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__

    |     await self.middleware_stack(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app

    |     await route.handle(scope, receive, send)

    |     await app(scope, receive, sender)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    |     response = await f(request)

    |                ^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app

    |     raw_response = await run_endpoint_function(

    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function

    |     return await dependant.call(**values)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/users.py", line 108, in patch_user

    |     return await update_user(user_db, user_update, session)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 32, in update_user

    |     user_db = await get_user_by_id(db, user_id)

    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 23, in get_user_by_id

    |     return (await db.exec(stmt)).first()

    |                   ^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 891, in __getattr__

    |     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

    | AttributeError: 'User' object has no attribute 'exec'

    +------------------------------------


During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    return await self.app(scope, receive, send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 745, in __call__

    await self.app(scope, otel_receive, otel_send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

    response = await self.dispatch_func(request, call_next)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 99, in dispatch

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 376, in flatten_query_string_lists

    response = await call_next(request)

    return await call_next(request)

               ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

           ^^^^^^^^^^^^^^^^^^^^^^^^


File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__

    await self.simple_response(scope, receive, send, request_headers=headers)

    raise app_exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 366, in check_boundary

    return await call_next(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/middleware.py", line 59, in __call__

    await self.app(scope, wrapper, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 32, in update_user

    user_db = await get_user_by_id(db, user_id)

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 23, in get_user_by_id

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    return (await db.exec(stmt)).first()

    await app(scope, receive, sender)

                  ^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__

  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 891, in __getattr__

    await self.middleware_stack(scope, receive, send)

    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app

    await route.handle(scope, receive, send)

AttributeError: 'User' object has no attribute 'exec'

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

  await self.app(scope, receive, send)

                             unhandled error: 'User' object has no              

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

                             attribute 'exec'                                   

    await wrap_app_handling_exceptions(app, request)(scope, receive, send)

Exception in ASGI application

  + Exception Group Traceback (most recent call last):

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 76, in collapse_excgroups

    raise exc

  |     yield

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 177, in __call__

    await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    response = await f(request)

               ^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app

    raw_response = await run_endpoint_function(

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function

    return await dependant.call(**values)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/users.py", line 108, in patch_user

    return await update_user(user_db, user_update, session)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  |     async with anyio.create_task_group() as task_group:

  |                ^^^^^^^^^^^^^^^^^^^^^^^^^

  |   File "/app/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 772, in __aexit__

  |     raise BaseExceptionGroup(

  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)

  +-+---------------- 1 ----------------

    | Traceback (most recent call last):

    |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi

    |     result = await app(  # type: ignore[func-returns-value]

    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    |     return await self.app(scope, receive, send)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__

    |     await super().__call__(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__

    |     await self.middleware_stack(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    |     await self.app(scope, receive, _send)

    |   File "/app/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 745, in __call__

    |     await self.app(scope, otel_receive, otel_send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    |     await self.app(scope, receive, _send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^




File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 376, in flatten_query_string_lists

    |     return await call_next(request)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 366, in check_boundary

    |     return await call_next(request)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    +------------------------------------

    |     response = await self.dispatch_func(request, call_next)

    |     return await dependant.call(**values)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 99, in dispatch

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception, another exception occurred:

    |     response = await call_next(request)

    |     raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__

Traceback (most recent call last):


          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |                ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/users.py", line 108, in patch_user

    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     return await update_user(user_db, user_update, session)

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 23, in get_user_by_id

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function

    return await self.app(scope, receive, send)

    result = await app(  # type: ignore[func-returns-value]

    await self.app(scope, receive, send)

    |     raise app_exc

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/middleware.py", line 59, in __call__

    |     return (await db.exec(stmt)).first()

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 32, in update_user

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

  File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__

    await self.app(scope, wrapper, send)

    |     user_db = await get_user_by_id(db, user_id)

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    await super().__call__(scope, receive, send)

    |                   ^^^^^^^

    raise exc

    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

           ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__

                                   ^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 891, in __getattr__

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

  File "/app/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 745, in __call__

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    response = await self.dispatch_func(request, call_next)

    |     await self.simple_response(scope, receive, send, request_headers=headers)

    |     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

    raise app_exc

    await self.app(scope, otel_receive, otel_send)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    | AttributeError: 'User' object has no attribute 'exec'

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 366, in check_boundary

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    await self.app(scope, receive_or_disconnect, send_no_error)

    |     await self.app(scope, receive, send)

    return await call_next(request)

  raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/middleware.py", line 59, in __call__

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    raise exc

    |     await self.app(scope, wrapper, send)

    await self.app(scope, receive_or_disconnect, send_no_error)

    await self.app(scope, receive, _send)

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 376, in flatten_query_string_lists

               ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    return await call_next(request)

    response = await self.dispatch_func(request, call_next)

    with recv_stream, send_stream, collapse_excgroups():

    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    await self.app(scope, receive, _send)

    with recv_stream, send_stream, collapse_excgroups():

    raise app_exc

           ^^^^^^^^^^^^^^^^^^^^^^^^

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 99, in dispatch

    |     raise exc

    await self.app(scope, receive_or_disconnect, send_no_error)

    response = await call_next(request)

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    raise app_exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__

    self.gen.throw(value)

    |     await app(scope, receive, sender)

    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

    await self.simple_response(scope, receive, send, request_headers=headers)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__

    await app(scope, receive, sender)

    return await dependant.call(**values)

    raise exc



  |     await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    response = await f(request)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/users.py", line 108, in patch_user

    await app(scope, receive, sender)

    |     await route.handle(scope, receive, send)

               ^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app

    |     await self.app(scope, receive, send)

    raw_response = await run_endpoint_function(

    return await update_user(user_db, user_update, session)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    await self.middleware_stack(scope, receive, send)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 32, in update_user

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app

    user_db = await get_user_by_id(db, user_id)

    |     raise exc

    await route.handle(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |     await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 23, in get_user_by_id

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    return (await db.exec(stmt)).first()

    |     response = await f(request)

    await self.app(scope, receive, send)

    |                ^^^^^^^^^^^^^^^^

                  ^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 891, in __getattr__

    await wrap_app_handling_exceptions(app, request)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 32, in update_user

[08/18/25 01:33:54] ERROR    2025-08-18 01:33:54 - ERROR    - main - main.py:412

                             unhandled error: 'User' object has no              

                             attribute 'exec'                                   

Exception in ASGI application

  + Exception Group Traceback (most recent call last):

  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 76, in collapse_excgroups

  |     yield

  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 177, in __call__

  |     async with anyio.create_task_group() as task_group:

  |                ^^^^^^^^^^^^^^^^^^^^^^^^^

  |   File "/app/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 772, in __aexit__

  |     raise BaseExceptionGroup(



ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)

  +-+---------------- 1 ----------------

    | Traceback (most recent call last):

    |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi

    |     result = await app(  # type: ignore[func-returns-value]

    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    |     return await self.app(scope, receive, send)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__

    |     await super().__call__(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__

    |     await self.middleware_stack(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    |     await self.app(scope, receive, _send)

    |   File "/app/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 745, in __call__

    |     await self.app(scope, otel_receive, otel_send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    |     await self.app(scope, receive, _send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 376, in flatten_query_string_lists

    |     return await call_next(request)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 891, in __getattr__

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 366, in check_boundary

    |     return await call_next(request)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc



File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    |     response = await self.dispatch_func(request, call_next)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 99, in dispatch

    |     response = await call_next(request)

    |                ^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    |     raise app_exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    |     await self.app(scope, receive_or_disconnect, send_no_error)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__

    |     await self.simple_response(scope, receive, send, request_headers=headers)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    |     await self.app(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/middleware.py", line 59, in __call__

    |     await self.app(scope, wrapper, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    |     raise exc

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    |     await app(scope, receive, sender)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__

    |     await self.middleware_stack(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app

    |     await route.handle(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

    |     await self.app(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

    | AttributeError: 'User' object has no attribute 'exec'

    +------------------------------------

    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)

 

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

During handling of the above exception, another exception occurred:

    |     raise exc

 

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

Traceback (most recent call last):

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |     await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    return await self.app(scope, receive, send)

    |     response = await f(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |                ^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app

    await super().__call__(scope, receive, send)

    |     raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__

    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    await self.middleware_stack(scope, receive, send)

    |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    |     return await dependant.call(**values)

    raise exc

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/users.py", line 108, in patch_user

    await self.app(scope, receive, _send)


  return await update_user(user_db, user_update, session)

  File "/app/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 745, in __call__

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    await self.app(scope, otel_receive, otel_send)

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 32, in update_user

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__

    |     user_db = await get_user_by_id(db, user_id)

    raise exc

    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__

    |   File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 23, in get_user_by_id

    await self.app(scope, receive, _send)

    |     return (await db.exec(stmt)).first()

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    |                   ^^^^^^^

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 376, in flatten_query_string_lists

    return await call_next(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 366, in check_boundary

    return await call_next(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 176, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 178, in __call__

    response = await self.dispatch_func(request, call_next)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 99, in dispatch

    response = await call_next(request)

               ^^^^^^^^^^^^^^^^^^^^^^^^


 File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 156, in call_next

    raise app_exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 141, in coro

    await self.app(scope, receive_or_disconnect, send_no_error)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__

    await self.simple_response(scope, receive, send, request_headers=headers)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/middleware.py", line 59, in __call__

    await self.app(scope, wrapper, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

    await wrap_app_handling_exceptions(app, request)(scope, receive, send)

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    await app(scope, receive, sender)

  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    response = await f(request)

               ^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app

    raw_response = await run_endpoint_function(

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function

    return await dependant.call(**values)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/users.py", line 108, in patch_user

    return await update_user(user_db, user_update, session)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 32, in update_user

    user_db = await get_user_by_id(db, user_id)

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/database/models/user/crud.py", line 23, in get_user_by_id

    return (await db.exec(stmt)).first()

                  ^^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 891, in __getattr__

    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

AttributeError: 'User' object has no attribute 'exec'

Railway rate limit of 500 logs/sec reached for replica, update your application to reduce the logging rate. Messages dropped: 253































